### PR TITLE
 Fix NullPointerException caused by transaction release

### LINKED ISSUE #2898: StandardJanusGraphTx::expireSchemaElement throws NPE due to race condition
For confirmed bugs, please report:
- Version: 0.6.0, master
- Storage Backend: doesn't matter
- Mixed Index Backend: doesn't matter
- Current Behavior: No NPE should be thrown

I was running [this benchmark](https://gist.github.com/li-boxuan/98d4dc18215e28b239c7433c8c39fb3f) and encountered NPE on v0.6 and master branches (provided that I changed concurrency in https://github.com/JanusGraph/janusgraph/blob/e64facbcdefd9d63ede4bedfbf15b78dc56d4751/janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java#L430-L435 from 1 to 8).

The exception trace is:

```
java.lang.NullPointerException
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.expireSchemaElement(StandardJanusGraphTx.java:1593)
	at org.janusgraph.graphdb.database.management.ManagementLogger.read(ManagementLogger.java:97)
	at org.janusgraph.diskstorage.log.util.ProcessMessageJob.run(ProcessMessageJob.java:46)
```

Apparently, `vertexCache` is null because the transaction has already been closed.

This bug was uncovered by 0.6.0 (08fd019) because now the internal resources are cleared after the transaction gets closed.

The cause is a race condition. Right after `graph.getOpenTransactions()` is invoked in ManagementLogger, the transaction could be released (i.e. `releaseTransaction()` being called) concurrently. Then, when ManagementLogger calls `expireSchemaElement` method for that transaction, NPE occurs.

This is similar to the bug discussed in https://lists.lfaidata.foundation/g/janusgraph-users/topic/potential_transaction_issue/85970858, where NPEs occur because some transaction internal structures are accessed even if the transaction has already been closed. Nonetheless, it is not yet clear what is the exact reason for this NPE.

### PR DESCRIPTION
**Pull request by li-boxuan**
Fixes JanusGraph#2898. Due to a race condition, vertexCache could be cleared before
it is accessed. To avoid NPEs, we cannot simply assign null to vertexCache
to release the memory.

This commit also surpresses https://lists.lfaidata.foundation/g/janusgraph-users/topic/potential_transaction_issue/85970858
by using a dummy empty vertexCache after transaction release. The root cause
for this bug is unknown, but likely it is due to another race condition.
To keep the behavior consistent with v0.5 and before, this commit surpresses
this issue and writes a warning log whenever the issue happens.

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Review by farodin91 — APPROVED** [review]
LGTM! Thank you @li-boxuan.

File: janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java [hunk 1]
```diff
@@ -504,6 +504,10 @@ private InternalVertex getExistingVertex(long vertexId) {
     }
 
     public InternalVertex getInternalVertex(long vertexId) {
+        if (vertexCache == null) {
```
Comment (rngcntr) [inline janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java:507]: The class `StandardJanusGraphTx` already has a `verifyOpen()` method, which checks `isClosed()` and throws an exception if the transaction is closed. I quickly skimmed the `StandardJanusGraphTx` class and it looks to me like `isClosed()` is always equal to `vertexCache == null`, `addedRelations == null` and `deletedRelations == null`, but it's way more readable.

I suggest to add a `warnIfClosed()` method and call it here and also in `getExistingVertex()`, `getInternalVertices()`, `connectRelation()`, `getSchemaVertex()` and `expireSchemaElement()`.

File: janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java [hunk 2]
```diff
@@ -1582,11 +1586,12 @@ public final boolean isClosed() {
 
     @Override
     public boolean hasModifications() {
-        return !addedRelations.isEmpty() || !deletedRelations.isEmpty();
+        return addedRelations != null && deletedRelations != null && (!addedRelations.isEmpty() || !deletedRelations.isEmpty());
```
Comment (rngcntr) [inline janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java:1589]:
```suggestion
        return isOpen() && (!addedRelations.isEmpty() || !deletedRelations.isEmpty());
```

File: janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java (hunk 1 above)
Comment (rngcntr) [reply janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java:507]: I don't know exactly how transactions are handled between threads, but if multiple threads can access the same transaction, we need to synchronize state-changing calls to the same transaction.

Comment (li-boxuan) [reply janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java:507]: > if multiple threads can access the same transaction, we need to synchronize state-changing calls to the same transaction

TBH I am not sure if race condition is the cause for the NPE in `getInternalVertex`.

Comment (rngcntr) [reply janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java:507]: Me neither and it's hard to debug as well

Comment (li-boxuan) [reply janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java]: I now assign a dummy empty cache to the variable `vertexCache` in transaction release method.

**Review by rngcntr — APPROVED** [review]

**Comment by li-boxuan** [comment]
@rngcntr That's great! Did you also find the root cause for https://lists.lfaidata.foundation/g/janusgraph-users/topic/potential_transaction_issue/85970858? In other words, how does it happen that users accidentally use a closed transaction?

**Comment by rngcntr** [comment]
@li-boxuan The thread you mention sounds very similar to the problem we were facing prior to the fix. The issue was that the TinkerPop framework called another `hasNext()` on each traversal after its transaction has been committed. In most cases, this is not a problem for us, but sometimes - especially when using `limit()` steps - we observe race conditions.

**Comment by li-boxuan** [comment]
@rngcntr Thanks, what you said is very likely to be true - since both users reported that they were using the TinkerPop server.
