### PR TITLE
Drop benchmark graph data after CQLMultiQueryDropBenchmark

### LINKED ISSUE #4434: Benchmark tests are failing
Seems after we added `CQLMultiQueryDropBenchmark` benchmark test in [this commit](https://github.com/JanusGraph/janusgraph/commit/c3bdf6189d1ce1dc51334b8a214a1beb821da717) the test which runs after it (currently `CQLMultiQueryMultiSlicesBenchmark`) is failing.

It seems the problem is that the data of `CQLMultiQueryDropBenchmark` is not removed, but the data of other tests are removed with `JanusGraphFactory.drop(graph);` after each test execution.

For confirmed bugs, please report:

- Version: master
- Storage Backend: cql
- Mixed Index Backend: none
- Expected Behavior: benchmark test passes
- Current Behavior: benchmark test fails due to an error
- Steps to Reproduce: Execute benchmark tests for `CQLMultiQueryDropBenchmark`

### Stack Trace (if you have one)

```
Result "org.janusgraph.CQLMultiQueryDropBenchmark.dropVertices":
  1422.933 ±(99.9%) 101.241 ms/op [Average]
  (min, avg, max) = (1401.601, 1422.933, 1463.275), stdev = 26.292
  CI (99.9%): [1321.692, 1524.173] (assumes normal distribution)


# JMH version: 1.37
# VM version: JDK 1.8.0_412, OpenJDK 64-Bit Server VM, 25.412-b08
# VM invoker: /opt/hostedtoolcache/Java_Zulu_jdk/8.0.412-8/x64/jre/bin/java
# VM options: <none>
# Blackhole mode: full + dont-inline hint (auto-detected, use -Djmh.blackhole.autoDetect=false to disable)
# Warmup: 2 iterations, 1 s each
# Measurement: 5 iterations, 5 s each
# Timeout: 10 min per iteration
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Average time, time/op
# Benchmark: org.janusgraph.CQLMultiQueryMultiSlicesBenchmark.getValuesAllPropertiesWithAllMultiQuerySlicesUnderMaxRequestsPerConnection
# Parameters: (propertyCardinalitySingle = true, verticesAmount = 5000)

# Run progress: 48.15% complete, ETA 00:29:25
# Fork: 1 of 1
# Warmup Iteration   1: <failure>

org.janusgraph.core.SchemaViolationException: Adding this property for key [~T$SchemaName] and value [rtname] violates a uniqueness constraint [SystemIndex#~T$SchemaName]
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.addProperty(StandardJanusGraphTx.java:976)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.addProperty(StandardJanusGraphTx.java:897)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.addProperty(StandardJanusGraphTx.java:893)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.makeSchemaVertex(StandardJanusGraphTx.java:1030)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.makePropertyKey(StandardJanusGraphTx.java:1049)
	at org.janusgraph.graphdb.types.StandardPropertyKeyMaker.make(StandardPropertyKeyMaker.java:114)
	at org.janusgraph.CQLMultiQueryMultiSlicesBenchmark.setUp(CQLMultiQueryMultiSlicesBenchmark.java:75)
	at org.janusgraph.jmh_generated.CQLMultiQueryMultiSlicesBenchmark_getValuesAllPropertiesWithAllMultiQuerySlicesUnderMaxRequestsPerConnection_jmhTest._jmh_tryInit_f_cqlmultiquerymultislicesbenchmark0_G(CQLMultiQueryMultiSlicesBenchmark_getValuesAllPropertiesWithAllMultiQuerySlicesUnderMaxRequestsPerConnection_jmhTest.java:451)
	at org.janusgraph.jmh_generated.CQLMultiQueryMultiSlicesBenchmark_getValuesAllPropertiesWithAllMultiQuerySlicesUnderMaxRequestsPerConnection_jmhTest.getValuesAllPropertiesWithAllMultiQuerySlicesUnderMaxRequestsPerConnection_AverageTime(CQLMultiQueryMultiSlicesBenchmark_getValuesAllPropertiesWithAllMultiQuerySlicesUnderMaxRequestsPerConnection_jmhTest.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:527)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:504)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)


<JMH had finished, but forked VM did not exit, are there stray running threads? Waiting 24 seconds more...>
```

### PR DESCRIPTION
**Pull request by porunov**
Fixes #4434

Passed benchmark tests of this PR: https://github.com/porunov/janusgraph/actions/runs/8959195234/job/24604366986

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

File: janusgraph-benchmark/src/main/java/org/janusgraph/CQLMultiQueryDropBenchmark.java [hunk 1]
```diff
@@ -71,33 +72,27 @@ public WriteConfiguration getConfiguration() {
     public void setUp() throws Exception {
         graph = JanusGraphFactory.open(getConfiguration());
 
-        boolean alreadyAdded = true;
         JanusGraphManagement mgmt = graph.openManagement();
-        if (!mgmt.containsPropertyKey("id")) {
```
Comment (ntisseyre) [inline janusgraph-benchmark/src/main/java/org/janusgraph/CQLMultiQueryDropBenchmark.java:76]: Wouldn't this run into error, that schema key already exists, when executing this benchmark test multiple times with different parameters?

Comment (porunov) [reply janusgraph-benchmark/src/main/java/org/janusgraph/CQLMultiQueryDropBenchmark.java:76]: No because after each execution we remove the whole graph via the below method `@TearDown`. You can see all the benchmark tests passed for this PR ([link](https://github.com/porunov/janusgraph/actions/runs/8959195234/job/24604366986)). Particular test results:
```
CQLMultiQueryDropBenchmark.dropVertices                                                                                       N/A           true                          N/A              5000  avgt    5     97.821 ±   21.607  ms/op
CQLMultiQueryDropBenchmark.dropVertices                                                                                       N/A          false                          N/A              5000  avgt    5   1407.599 ±   91.186  ms/op
```

We have one method annotated with `@Setup` and one method annotated with `@TearDown` in this class. Both have a default `Level.Trial` ([doc link](https://javadoc.io/doc/org.openjdk.jmh/jmh-core/0.5.2/org/openjdk/jmh/annotations/Level.html#Trial)). Meaning they will be executed for each run of the benchmark (i.e. once per each unique combination of the parameters. In other words 2 times only).
Thus we will first initialize database then run a benchmark iterations then remove database, re-initialize database and run the second benchmark.

The downside: We re-initialize database with the same schema and data two times (i.e. spend time for the same operations).
The upside: The test executions are mostly fair because underlying storage backend should give the same or similar internal cache hit/miss rate between different runs.

We use this technique for all  other benchmarks (i.e. database re-initialization between different benchmark executions).

**Review by ntisseyre — APPROVED** [review]
