### PR TITLE
Fix nested AND/OR profiler group issue

### LINKED ISSUE #2285: Profiler annotations are wrong when there are multiple backend queries
For confirmed bugs, please report:
- Version: 0.5.2, 0.6.0-SNAPSHOT
- Storage Backend: does not matter
- Mixed Index Backend: does not matter
- Steps to reproduce:
```groovy
graph = JanusGraphFactory.open("inmemory")
mgmt = graph.openManagement()
nameKey = mgmt.makePropertyKey('name').dataType(String.class).make()
ageKey = mgmt.makePropertyKey('age').dataType(Integer.class).make()
mgmt.buildIndex("name", Vertex.class).addKey(nameKey).buildCompositeIndex()
mgmt.buildIndex("age", Vertex.class).addKey(ageKey).buildCompositeIndex()
mgmt.commit()

g = graph.traversal()
g.addV().property("name", "bob").property("age", 60)
graph.tx().commit()
```

When there is more than one backend query, annotations (condition, orders, isFitted, isOrdered, query, index) of the last one overwrites previous annotations.

1. Multiple conditions under Or
```
g.V().or(has("name", "bob"), has("age", 60)).profile()

==>Traversal Metrics
Step                                                               Count  Traversers       Time (ms)    % Dur
=============================================================================================================
Or(JanusGraphStep([],[name.eq(bob)]),JanusGraph...                     1           1           5.852   100.00
    \_condition=(age = 60)
    \_orders=[]
    \_isFitted=true
    \_isOrdered=true
    \_query=multiKSQ[1]@2000
    \_index=age
  optimization                                                                                 0.621
  optimization                                                                                 0.175
  optimization                                                                                 0.129
  backend-query                                                        1                       0.730
    \_query=name:multiKSQ[1]@2000
    \_limit=2000
  backend-query                                                        1                       1.396
    \_query=age:multiKSQ[1]@2000
    \_limit=2000
                                            >TOTAL                     -           -           5.852        -
```
Note the following part   
```
   \_condition=(age = 60)
    \_orders=[]
    \_isFitted=true
    \_isOrdered=true
    \_query=multiKSQ[1]@2000
    \_index=age
```
only represents the second backend-query.

2. Multiple conditions under And
Same issue:
```
g.V().has("name", "bob").has("age", 60).profile()


==>Traversal Metrics
Step                                                               Count  Traversers       Time (ms)    % Dur
=============================================================================================================
JanusGraphStep([],[name.eq(bob), age.eq(60)])                          1           1           1.331   100.00
    \_condition=(name = bob AND age = 60)
    \_orders=[]
    \_isFitted=true
    \_isOrdered=true
    \_query=multiKSQ[1]@2147483647
    \_index=age
  optimization                                                                                 0.013
  optimization                                                                                 0.218
  backend-query                                                        1                       0.119
    \_query=age:multiKSQ[1]@2147483647
  backend-query                                                        1                       0.094
    \_query=name:multiKSQ[1]@2147483647
                                    >TOTAL                     -           -           1.331        -
```

### PR DESCRIPTION
**Pull request by li-boxuan**
Currently, when there is more than one backend query, annotations
(condition, orders, isFitted, isOrdered, query, index) of the last
one overwrites previous annotations in the profiling result.

This commit fixes this problem by avoiding flattening AND/OR query
groups. The drawback of this commit is those groups (AND-query, OR-query)
are not timed due to technical difficulty, which is left as future
work.

Fixes #2285

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Comment by li-boxuan** [comment]
```groovy
graph = JanusGraphFactory.open("conf/janusgraph-cql.properties")
mgmt = graph.openManagement()
nameKey = mgmt.makePropertyKey('name').dataType(String.class).make()
weightKey = mgmt.makePropertyKey('weight').dataType(Integer.class).make()
mgmt.buildIndex("nameIdx", Vertex.class).addKey(nameKey).buildCompositeIndex()
mgmt.buildIndex("weightIdx", Vertex.class).addKey(weightKey).buildCompositeIndex()
mgmt.commit()


g = graph.traversal()
for (i = 0; i < 10000; i++) {
g.addV().property("name", "value" + i % 5).property("weight", i % 100).next()
}
graph.tx().commit()

g.V().and(has("name", "bob"), has("weight", 100)).profile()
```

With this PR:
```
Step                                                               Count  Traversers       Time (ms)    % Dur
=============================================================================================================
JanusGraphStep([],[name.eq(bob), weight.eq(100)])                                             15.668   100.00
  constructGraphCentricQuery                                                                   0.110
  constructGraphCentricQuery                                                                   4.466
  GraphCentricQuery                                                                            4.964
    \_condition=(name = bob AND weight = 100)
    \_orders=[]
    \_isFitted=true
    \_isOrdered=true
    \_query=[weightIdx:multiKSQ[1]@2147483647, nameIdx:multiKSQ[1]@2147483647]
    AND-query                                                                                  0.000
    \_query=multiKSQ[1]@2147483647
    \_index=weightIdx
      backend-query                                                    0                       1.312
    \_query=weightIdx:multiKSQ[1]@2147483647
    AND-query                                                                                  0.000
    \_query=multiKSQ[1]@2147483647
    \_index=nameIdx
      backend-query                                                    0                       1.776
    \_query=nameIdx:multiKSQ[1]@2147483647
                                            >TOTAL                     -           -          15.668        -
```

Without this PR (0.6.0-SNAPSHOT):

```
Step                                                               Count  Traversers       Time (ms)    % Dur
=============================================================================================================
JanusGraphStep([],[name.eq(bob), weight.eq(100)])                                             22.087   100.00
  constructGraphCentricQuery                                                                   0.122
  constructGraphCentricQuery                                                                   5.454
  GraphCentricQuery                                                                            6.310
    \_condition=(name = bob AND weight = 100)
    \_orders=[]
    \_isFitted=true
    \_isOrdered=true
    \_query=multiKSQ[1]@2147483647
    \_index=weightIdx
    backend-query                                                      0                       1.608
    \_query=weightIdx:multiKSQ[1]@2147483647
    backend-query                                                      0                       1.573
    \_query=nameIdx:multiKSQ[1]@2147483647
                                            >TOTAL                     -           -          22.087        -
```

File: janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java [hunk 1]
```diff
@@ -5827,6 +5865,39 @@ public void testVertexCentricQueryProfiling() {
...
+        mMultiLabels.getAnnotations().remove("percentDur");
+        assertEquals(annotations, mMultiLabels.getAnnotations());
+        assertEquals(3, mMultiLabels.getNested().size());
+        Metrics friendMetrics = (Metrics) mMultiLabels.getNested().toArray()[1];
+        assertEquals("OR-query", friendMetrics.getName());
+        // FIXME: assertTrue(friendMetrics.getDuration(TimeUnit.MICROSECONDS) > 0);
+        annotations = new HashMap() {{
+            put("isFitted", "true");
+            put("isOrdered", "true");
+            put("query", "2069:byTime:SliceQuery[0xB0E0FF7FFFFF9B,0xB0E0FF7FFFFF9C)@2147483647"); // vertex-centric index utilized
```
Comment (rngcntr) [inline janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java:5889]: Not specific to this line, but I put it here as an example:

Although I like how much effort you put into testing the profiler output, I expect we will have a hard time adapting all test cases if TinkerPop only ever so slightly changes the format of the profiler output :sweat_smile: 
That's only a quick thought that came to my mind, not saying that I have any idea how to do it better.

**Review by rngcntr — APPROVED** [review]
LGTM. Have you reported the inconsistent indenting of the profiler outputs to the TP community?

And for the record: Could you roughly point out what you tried to profile the AND groups and why it didn't work? I think having your progress written down would make it easier to get started if one wants to start working on that again.

File: janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java (hunk 1 above)
Comment (li-boxuan) [reply janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java:5889]: I got your point. I totally understand sometimes a change detector is not a good test. However, I still did this because:
1) For this line specifically, we have to assert because otherwise there is no way to assert whether vertex-centric index is used or not. ("byTime" is the index name and "2069" is its encoded version. Btw I really don't want to include "2069" but I cannot do much about it unless I change how index meta-data is stored, which I don't want to touch at the moment due to risk concern). 
2) In general, there is no much Tinkerpop format specific thing here. All these string literals like "isFitted"/"isOrdered"/"query" are all JanusGraph annotations. The hex string "0xB0E0FF7FFFFF9B" is calculated by JanusGraph and it won't change unless we change the way JanusGraph stores data (which means this line effectively prevents people from accidentally changing data format, which might not be detected by other tests). Of course, if we literally test the output of profiling result in string format, as pasted in https://github.com/JanusGraph/janusgraph/pull/2410#issuecomment-770188509, it would be very sensitive to any small change to Tinkerpop format.
The major Tinkerpop-coupled thing is the structure, i.e. how things are grouped and nested. This is unavoidable and does make sense because JanusGraph profiling-relevant code is already coupled with Tinkerpop profiling-relevant components. 

Currently, there are some test cases checking profiling result, but those are very basic that only check, say, whether backend-query exists, whether a certain annotation exists. Thus I added these detailed tests. Let me know if you have another idea of how to test them.

**Comment by li-boxuan** [comment]
@rngcntr Thanks for the review. Regarding your comments:

> Have you reported the inconsistent indenting of the profiler outputs to the TP community?

Thanks for the reminder, just created https://issues.apache.org/jira/browse/TINKERPOP-2522

> And for the record: Could you roughly point out what you tried to profile the AND groups and why it didn't work? I think having your progress written down would make it easier to get started if one wants to start working on that again.

One challenge is when we only have one AND/OR group, we flatten it out. See TP3ProfileWrapper::addNested method. We can't start the timer in this case otherwise there will be a concurrent timer running exception (which means the same timer is started twice). This does not seem impossible but I don't find an elegant way.

Another and major challenge is literally when to start the timer. It seems not too difficult for GraphCentricQueries, e.g. https://github.com/JanusGraph/janusgraph/pull/2289/files#diff-ff8f4e813f94f5aa38780636c4b21d4a41af9319bdc21dedc2db9cc4dd4d603eR58-R64. However, there is no easy entry point for VertexCentricQueries. I tried to do it at https://github.com/JanusGraph/janusgraph/pull/2289/files#diff-f75522d87e7db3974e2aa6ff3fb79182cef2991b8e937293a22bcfc87f1484bcR100 but led to a concurrent timer running exception.

**Comment by li-boxuan** [comment]
@porunov Would you like to review this PR, given you reviewed https://github.com/JanusGraph/janusgraph/pull/2289 earlier?

**Review by porunov — APPROVED** [review]
LGTM. Thank you @li-boxuan .
That said, I'm on a vacation for the next 2 weeks, thus please take my reviews with a grain of salt. I simply checked the code quickly on my phone with no any testing.

**Comment by li-boxuan** [comment]
Rebased to activate codecov check.

**Comment by li-boxuan** [comment]
I will merge this PR at this weekend if there is no further review.

**Comment by li-boxuan** [comment]
https://issues.apache.org/jira/browse/TINKERPOP-2522 is merged and will be released in 3.6.0.
