### PR TITLE
Fix two unit tests failing locally

### LINKED ISSUE #4139: JanusGraph v1.0 unit tests failing when ran locally
# Description
Running unit tests from a fresh clone of JanusGraph v1.0 fails locally.

# Steps to reproduce
```
$ git clone https://github.com/janusgraph/janusgraph.git
$ cd janusgraph/
$ git checkout v1.0
$ jenv local zulu64-11.0.21
$ mvn clean test \
    -pl janusgraph-driver,janusgraph-core \
    -Dgpg.skip -Drat.skip
...
<janusgraph-driver tests pass>
<janusgraph-core CompletableFutureUtilTest fails - see stacktrace below>
<janusgraph-core MultiQueriableStepBatchFetcherTest fails - see stacktrace below>
<janusgraph-core other tests pass>
```

- [Stacktrace for CompletableFutureUtilTest](https://github.com/JanusGraph/janusgraph/files/13461093/CompletableFutureUtilTest.failure.txt)
- [Stacktrace for MultiQueriableStepBatchFetcherTest](https://github.com/JanusGraph/janusgraph/files/13461095/MultiQueriableStepBatchFetcherTest.failure.log)

### PR DESCRIPTION
**Pull request by cdegroc**
Fixes #4139

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there an issue associated with this PR? Is it referenced in the commit message?
- [X] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [X] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

File: janusgraph-core/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/MultiQueriableStepBatchFetcherTest.java [hunk 1]
```diff
@@ -46,7 +48,7 @@ public void setupMocks(){
         Mockito.doReturn(traversal).when(traversal).asAdmin();
         Mockito.doReturn(Optional.of(tx)).when(traversal).getGraph();
         Mockito.doReturn(true).when(tx).isOpen();
-        Mockito.doReturn(multiQuery).when(tx).multiQuery();
+        Mockito.doReturn(multiQuery).when(tx).multiQuery(anyCollection());
```
Comment (cdegroc) [inline janusgraph-core/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/MultiQueriableStepBatchFetcherTest.java:51]: **💭 thought:** When not specifying the `multiQuery()` argument type, the mocked method return‏s null (in my tests). Could it be because that method is overloaded and accepts both a Collection and varargs?

File: janusgraph-core/src/test/java/org/janusgraph/diskstorage/util/CompletableFutureUtilTest.java [hunk 2]
```diff
@@ -124,13 +124,11 @@ public void shouldFailMapUnwrapWithSuppressedExceptions() {
...
-        Assertions.assertTrue(executionException.getCause() instanceof IllegalStateException);
-        Throwable[] suppressedExceptions = executionException.getSuppressed();
+        IllegalStateException exception = Assertions.assertThrows(IllegalStateException.class, () -> unwrap(futureMap));
+        Throwable[] suppressedExceptions = exception.getSuppressed();
         Assertions.assertEquals(10, suppressedExceptions.length);
         for(int i=0; i<10; i++){
-            Assertions.assertTrue(suppressedExceptions[i] instanceof ExecutionException &&
-                suppressedExceptions[i].getCause() instanceof IllegalArgumentException);
+            Assertions.assertTrue(suppressedExceptions[i] instanceof IllegalArgumentException);
         }
```
Comment (cdegroc) [inline janusgraph-core/src/test/java/org/janusgraph/diskstorage/util/CompletableFutureUtilTest.java:132]: 📝 Based on the code of `CompletableFutureUtil#unwrap` and `CompletableFutureUtil#unwrapExecutionException`, it would make sense to me that the exceptions returned are not `ExecutionException`s but their "unwrapped" counterpart (`IllegalStateException` or `IllegalArgumentException`).

Comment (porunov) [reply janusgraph-core/src/test/java/org/janusgraph/diskstorage/util/CompletableFutureUtilTest.java:132]: You are right. Sorry I forgot to change that previously. Initially it was returning ExecutionException but after some fixed I changed this behavior and completely forgot about these Unit tests.

**Review by porunov — APPROVED** [review]
LGTM. Thank you @cdegroc !

**Comment by janusgraph-automations** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|v1.0|[](https://github.com/JanusGraph/janusgraph/pull/4159)|

Note: Successful backport PRs will be merged automatically after passing CI.

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/JanusGraph/janusgraph/actions/runs/7049165796) for details
