### PR TITLE
Fix IndexOutOfBoundsException when read geoshape point by GraphBinary…

### LINKED ISSUE #3181: GraphBinaryMessageSerializerV1 cause a geoshape-read error
In a certain situation, reading a geoshape point by GraphBinaryMessageSerializerV1 will cause an IndexOutOfBoundsException. But in some situation is ok. For example:

- correct geoshape point
```
29.7154387159,120.20480209799999
29.7154387134,120.20480209799999
29.7154387334,120.20480209799999
29.7154387334,120.2048
29.7154387334,29.7154387334
29.71543872,29.7154387334
29.715438723,29.7154387334
29.7154387233,29.7154387334
```
- error geoshape point
```
29.7154388159,120.20480209799999
29.7154387234,120.20480209799999
29.7154387234,120.2048
29.7154387334,29.7154387234
29.7154387234,29.7154387334
29.7154387235,29.7154387334
```
 janusgraph client configutation:
```
hosts: [0.0.0.0]
port: 8182
serializer: {
    className: org.apache.tinkerpop.gremlin.driver.ser.GraphBinaryMessageSerializerV1,
    config: {
        ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry]
    }
}
```
For confirmed bugs, please report:

- Version: 0.6.0, 0.6.1, 0.6.2
- Storage Backend: hbase
- Mixed Index Backend: elasticsearch
- Link to discussed bug: 
- Expected Behavior:
- Current Behavior:
- Steps to Reproduce:

### Stack Trace (if you have one)

```
2022-08-15 11:38:51,021 ERROR [https-jsse-nio-8888-exec-3] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.util.concurrent.CompletionException: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(299) + length(4) exceeds writerIndex(299): CompositeByteBuf(ridx: 299, widx: 299, cap: 299, components=1)] with root cause
java.lang.IndexOutOfBoundsException: readerIndex(299) + length(4) exceeds writerIndex(299): CompositeByteBuf(ridx: 299, widx: 299, cap: 299, components=1)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1478)
        at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:811)
        at org.apache.tinkerpop.gremlin.driver.ser.NettyBuffer.readInt(NettyBuffer.java:112)
        at org.janusgraph.graphdb.tinkerpop.io.binary.GeoshapeGraphBinarySerializer$BufferInputStream.read(GeoshapeGraphBinarySerializer.java:41)
        at java.base/java.io.InputStream.read(InputStream.java:280)
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:200)
        at java.base/java.io.DataInputStream.readLong(DataInputStream.java:421)
        at java.base/java.io.DataInputStream.readDouble(DataInputStream.java:473)
        at org.locationtech.spatial4j.io.BinaryCodec.readDim(BinaryCodec.java:109)
        at org.locationtech.spatial4j.io.jts.JtsBinaryCodec.readDim(JtsBinaryCodec.java:46)
        at org.locationtech.spatial4j.io.BinaryCodec.readPoint(BinaryCodec.java:117)
        at org.locationtech.spatial4j.io.BinaryCodec.readShapeByTypeIfSupported(BinaryCodec.java:66)
        at org.locationtech.spatial4j.io.jts.JtsBinaryCodec.readShapeByTypeIfSupported(JtsBinaryCodec.java:69)
        at org.locationtech.spatial4j.io.BinaryCodec.readShape(BinaryCodec.java:52)
        at org.janusgraph.core.attribute.JtsGeoshapeHelper.readShape(JtsGeoshapeHelper.java:95)
        at org.janusgraph.core.attribute.Geoshape$GeoshapeBinarySerializer.read(Geoshape.java:625)
        at org.janusgraph.graphdb.tinkerpop.io.binary.GeoshapeGraphBinarySerializer.readNonNullableValue(GeoshapeGraphBinarySerializer.java:48)
        at org.janusgraph.graphdb.tinkerpop.io.binary.GeoshapeGraphBinarySerializer.readNonNullableValue(GeoshapeGraphBinarySerializer.java:26)
        at org.janusgraph.graphdb.tinkerpop.io.binary.JanusGraphTypeSerializer.readValue(JanusGraphTypeSerializer.java:63)
        at org.janusgraph.graphdb.tinkerpop.io.binary.JanusGraphTypeSerializer.read(JanusGraphTypeSerializer.java:52)
        at org.apache.tinkerpop.gremlin.structure.io.binary.GraphBinaryReader.read(GraphBinaryReader.java:106)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.CollectionSerializer.readValue(CollectionSerializer.java:41)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.ListSerializer.readValue(ListSerializer.java:39)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.ListSerializer.readValue(ListSerializer.java:29)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.SimpleTypeSerializer.readValue(SimpleTypeSerializer.java:59)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.SimpleTypeSerializer.read(SimpleTypeSerializer.java:47)
        at org.apache.tinkerpop.gremlin.structure.io.binary.GraphBinaryReader.read(GraphBinaryReader.java:106)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.MapSerializer.readValue(MapSerializer.java:42)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.MapSerializer.readValue(MapSerializer.java:31)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.SimpleTypeSerializer.readValue(SimpleTypeSerializer.java:59)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.SimpleTypeSerializer.read(SimpleTypeSerializer.java:47)
        at org.apache.tinkerpop.gremlin.structure.io.binary.GraphBinaryReader.read(GraphBinaryReader.java:106)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.TraverserSerializer.readValue(TraverserSerializer.java:42)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.TraverserSerializer.readValue(TraverserSerializer.java:33)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.SimpleTypeSerializer.readValue(SimpleTypeSerializer.java:59)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.SimpleTypeSerializer.read(SimpleTypeSerializer.java:47)
        at org.apache.tinkerpop.gremlin.structure.io.binary.GraphBinaryReader.read(GraphBinaryReader.java:106)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.CollectionSerializer.readValue(CollectionSerializer.java:41)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.ListSerializer.readValue(ListSerializer.java:39)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.ListSerializer.readValue(ListSerializer.java:29)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.SimpleTypeSerializer.readValue(SimpleTypeSerializer.java:59)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.SimpleTypeSerializer.read(SimpleTypeSerializer.java:47)
        at org.apache.tinkerpop.gremlin.structure.io.binary.GraphBinaryReader.read(GraphBinaryReader.java:106)
        at org.apache.tinkerpop.gremlin.driver.ser.binary.ResponseMessageSerializer.readValue(ResponseMessageSerializer.java:56)
        at org.apache.tinkerpop.gremlin.driver.ser.GraphBinaryMessageSerializerV1.deserializeResponse(GraphBinaryMessageSerializerV1.java:180)
        at org.apache.tinkerpop.gremlin.driver.handler.WebSocketGremlinResponseDecoder.decode(WebSocketGremlinResponseDecoder.java:47)
        at org.apache.tinkerpop.gremlin.driver.handler.WebSocketGremlinResponseDecoder.decode(WebSocketGremlinResponseDecoder.java:35)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)

```

### PR DESCRIPTION
**Pull request by dh-cloud**
…MessageSerializerV1.

The root cause of this problem is due to BufferInputStream.class in
GeoshapeGraphBinarySerializer.java extends InputStream.class, it overrides
the superclass's read() method, but not Overrides superclass's
read(byte b[], int off, int len) method.

If BufferInputStream.class's read() returns -1, InputStream::read(byte b[]
, int off, int len) will break its for loop, so cause IndexOutOfBoundsException
finally.

This PR fixes #3181.

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Comment by FlorianHockmann** [comment]
Thanks a lot for this contribution, @dh-cloud! Could you please [sign the Developer Certificate of Origin](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md#commit-changes-and-sign-the-developer-certificate-of-origin)? That should make the DCO check green in this PR.

Apart from that, could you please create a test case that fails without your PR but passes with your fix? I guess that should be possible with the examples that you already provided in the linked issue? You can find existing tests for the GraphBinary serialization of Geoshapes [here](https://github.com/JanusGraph/janusgraph/blob/v0.6/janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/io/binary/GeoshapeGraphBinarySerializerTest.java#L45).

We have also completely rewritten the GraphBinary serialization of Geoshapes on `master` which will be released with version 1.0.0: #2876. So, if you want, you could also create an additional PR that targets `master` and adds the additional test cases there to see whether we also have the bug in there. But you don't have to do that of course. I can also do that after we have reviewed this PR.

File: janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/GeoshapeGraphBinarySerializer.java [hunk 1]
```diff
@@ -40,6 +40,28 @@ public BufferInputStream(Buffer buffer) {
         public int read() {
             return buffer.readInt();
         }
+
+        @Override
+        public int read(byte b[], int off, int len) {
```
Comment (porunov) [inline janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/GeoshapeGraphBinarySerializer.java:45]: Code style linter doesn't allow braces to be at C style position. Thus, all tests fail.
To fix that you need to replace `byte b[]` here with `byte[] b`.

**Review by porunov — COMMENTED** [review]
Thank you @dh-cloud for the contribution! Below is a code style problem which causes linter to fail

File: janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/GeoshapeGraphBinarySerializer.java [hunk 2]
```diff
@@ -40,6 +40,28 @@ public BufferInputStream(Buffer buffer) {
...
+            int c = read();
+            b[off] = (byte) c;
+
+            int i = 1;
+
+            for (; i < len; i++) {
+                c = read();
+                b[off + i] = (byte) c;
+            }
+            return i;
```
Comment (porunov) [inline janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/GeoshapeGraphBinarySerializer.java:63]: (_nitpick_) - Not necessary to resolve because this part of code was copied from InputStream implementation.

As I understand previously you could read less data then the `len` but now we always read exactly `len` amount of data. So, I guess this could be simplified a little bit.
```
for(int i=0;i<len;i++){
    b[off+i] = (byte) read();
}
return len;
```

**Review by porunov — APPROVED** [review]
LGTM. Thank you @dh-cloud !
I have only one nitpick below which isn't necessary to be resolved.
Another thing I want to ask is to rebase your PR against the latest commit in `v0.6` branch. There was a bugfix in HBase CI tests. If we run tests for your PR now without that bugfix they will fail.
I.e. all you need to do is the following:
```
git remote add upstream https://github.com/JanusGraph/janusgraph
git fetch upstream v0.6
git rebase upstream/v0.6
git push -f
```

**Review by FlorianHockmann — APPROVED** [review]
Thanks again for fixing this, @dh-cloud! I just reviewed the changes and also tried out whether the problem also exists with our rewritten implementation on `master`, but the tests you changed still pass there, so it seems unaffected.
