### PR TITLE
RelationIdentifierGraphBinarySerializer: Fix property serialization

### LINKED ISSUE #3454: RelationIdentifierGraphBinarySerializer fails to serialize properties
As reported by @gdotv on Discord, GraphBinarySerializer fails to serialize & deserialize properties. An example would be:

`conf/remote.yaml`:
```
hosts: [localhost]
port: 8182
serializer: { className: org.apache.tinkerpop.gremlin.driver.ser.GraphBinaryMessageSerializerV1, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
```

Insert some vertices:
```
g.addV('person').
  property(single, 'age', 29).
  property(single, 'name', "marko").
  addV('person').
  property(single, 'age', 27).
  property(single, 'name', "vadas").
  addV('software').
  property(single, 'lang', "java").
  property(single, 'name', "lop").
  addV('person').
  property(single, 'age', 32).
  property(single, 'name', "josh").
  addV('software').
  property(single, 'lang', "java").
  property(single, 'name', "ripple").
  addV('person').
  property(single, 'age', 35).
  property(single, 'name', "peter")
```

Query all properties:
```
gremlin> :> g.V().properties()
Server could not serialize the result requested. Server error - Error during serialization: java.lang.NullPointerException. Note that the class must be serializable by the client and server for proper operation.
```

I was able to reproduce it on 1.0-rc1. The bug is caused by `RelationIdentifierGraphBinarySerializer`, which does not consider properties would have `inVertexId` to be null.

### PR DESCRIPTION
**Pull request by li-boxuan**
Fixes #3454

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

File: janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/RelationIdentifierGraphBinarySerializer.java [hunk 1]
```diff
@@ -40,6 +40,10 @@ protected void writeNonNullableValue(RelationIdentifier value, Buffer buffer, Gr
         buffer.writeLong(((Number) value.getOutVertexId()).longValue());
         buffer.writeLong(value.getTypeId());
         buffer.writeLong(value.getRelationId());
-        buffer.writeLong(((Number) value.getInVertexId()).longValue());
+        if (value.getInVertexId() != null) {
+            buffer.writeLong(((Number) value.getInVertexId()).longValue());
+        } else {
+            buffer.writeLong(0);
```
Comment (li-boxuan) [inline janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/RelationIdentifierGraphBinarySerializer.java:46]: Pretty sure this branch is covered by https://github.com/JanusGraph/janusgraph/actions/runs/3856024161/jobs/6571765068#step:6:310 but no idea why this is not captured by Codecov.

**Review by farodin91 — APPROVED** [review]
