### PR TITLE
Merge PR #1282 to master

### LINKED ISSUE #1165: Support list for Zookeeper URL for Solr cloud and index job
Reported on [janusgraph-users](https://groups.google.com/d/msg/janusgraph-users/x5CnYVpr1ls/BNfwNQ9dCAAJ)

```
15:44:17 WARN  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper  - Unable to create ZooKeeper Connection
java.net.UnknownHostException: [app01: invalid IPv6 address
```

Where the graph configuration properties

```
index.search.solr.zookeeper-url=app01:2181,app02:2181,app03:2181
```

The [`ZOOKEEPER_URL`](https://github.com/JanusGraph/janusgraph/blob/0.2/janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java#L161-L163) is defined as a `String` property rather than a `String[]` (for example, `storage.hostname` and `index.[X].solr.http-urls` use `String[]`). If the property allows a list, it would allow for a quorum of Zookeeper nodes to be specified.

### PR DESCRIPTION
**Pull request by jerryjch**
Fixes #1165 (merge to master)
-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [] Is there an issue associated with this PR? Is it referenced in the commit message?
- [] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

File: janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/MapReduceIndexManagement.java [hunk 1]
```diff
@@ -177,9 +178,9 @@ public MapReduceIndexManagement(JanusGraph g) {
         janusGraphMapReduceConfiguration.set(JanusGraphHadoopConfiguration.SCAN_JOB_CONFIG_ROOT,
                 GraphDatabaseConfiguration.class.getName() + "#JOB_NS");
         // Copy the StandardJanusGraph configuration under JanusGraphHadoopConfiguration.GRAPH_CONFIG_KEYS
-        org.apache.commons.configuration.Configuration localConfiguration = graph.getConfiguration().getLocalConfiguration();
-        localConfiguration.clearProperty(Graph.GRAPH);
-        copyInputKeys(hadoopConf, localConfiguration);
+        org.apache.commons.configuration.Configuration localc = graph.getConfiguration().getConfigurationAtOpen();
```
Comment (porunov) [inline janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/MapReduceIndexManagement.java]: In 0.2 this variable is called `localbc`, now it is renamed to `localc`. Is it OK?

Comment (jerryjch) [reply janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/MapReduceIndexManagement.java]: Do you mean it may cause merge problem later when people do merging from 0.2 to master again?
I thought it was a typo to have 'localbc', so I changed it to 'localc'.  Maybe it means 'local base configuration'.  But it is a trivial issue.

Comment (porunov) [reply janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/MapReduceIndexManagement.java]: I don't think that it will be a problem when merging from 0.2 into the master but the name isn't intuitively understandable for me. `localConfiguration` has more meaning for me than `localc` or `localbc`. But I agree that it isn't a big issue.

**Comment by jerryjch** [comment]
ok, @porunov I updated it to 'localConfiguration'.  Thanks for the review.

**Comment by jerryjch** [comment]
Thank you for the review!
