### PR TITLE
Pass HadoopManager through MetricInstrumentedStoreManager

### LINKED ISSUE #1958: MapReduce reindex fails when metrics.enabled=true - Seems to be due to StoreManager logic
- Version: JanusGraph 0.4.0
- Storage Backend: Hbase
- Mixed Index Backend: NA
- Mailing list Thread URL: https://groups.google.com/forum/#!topic/janusgraph-users/9vgLUms_kvk

I Noticed that MapReduce will fail if `metric.enabled=true` in the [graph configuration](https://www.google.com/url?q=https%3A%2F%2Fdocs.janusgraph.org%2Fbasics%2Fconfiguration-reference%2F%23metrics&sa=D&sntz=1&usg=AFQjCNGGjfb9LFiyEmjNxMNb-VMEQLhaDg).  Below is an example running two graphs – only difference between the two is the `metric.enabled` configuration field.

## metrics.enabled=false – Runs as expected

```
gremlin> graphMetricsDisabled.class
==>class org.janusgraph.graphdb.database.StandardJanusGraph

gremlin> graphMetricsDisabled.getBackend().getStoreManagerClass()
==>class org.janusgraph.diskstorage.hbase.HBaseStoreManager

```
Note above, the store manager class is set to hbase 

```
gremlin> mgmt = graphMetricsDisabled.openManagement()
==>org.janusgraph.graphdb.database.management.ManagementSystem@5182d7de

gremlin> mr = new org.janusgraph.hadoop.MapReduceIndexManagement(graphMetricsDisabled)
==>org.janusgraph.hadoop.MapReduceIndexManagement@7daa1f44

gremlin> mr.updateIndex(mgmt.getGraphIndex(newIndexName), SchemaAction.REINDEX).get()
==>org.janusgraph.hadoop.compat.h2.Hadoop2CountersScanMetrics@1482f718

```
Works!

## metrics.enabled=true – Fails

```
gremlin> graphMetricsEnabled.class
==>class org.janusgraph.graphdb.database.StandardJanusGraph

gremlin> graphMetricsEnabled.getBackend().getStoreManagerClass()
==>class org.janusgraph.diskstorage.util.MetricInstrumentedStoreManager
 ```
Note above, the store manager class is not set to hbase 

```
gremlin> mgmt = graphMetricsEnabled.openManagement()
==>org.janusgraph.graphdb.database.management.ManagementSystem@3774c48

gremlin> mr = new org.janusgraph.hadoop.MapReduceIndexManagement(graphMetricsEnabled)
==>org.janusgraph.hadoop.MapReduceIndexManagement@3138b98c

gremlin> mr.updateIndex(mgmt.getGraphIndex(newIndexName), SchemaAction.REINDEX).get()
Store manager class class org.janusgraph.diskstorage.util.MetricInstrumentedStoreManageris not supported
Type ':help' or ':h' for help.
Display stack trace? [yN]y
java.lang.IllegalArgumentException: Store manager class class org.janusgraph.diskstorage.util.MetricInstrumentedStoreManageris not supported
        at org.janusgraph.hadoop.MapReduceIndexManagement.updateIndex(MapReduceIndexManagement.java:164)
        at org.janusgraph.hadoop.MapReduceIndexManagement$updateIndex.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
        at Script272.run(Script272.groovy:1)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:674)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:376)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
        at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:266)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Digging into the source code, it appears the issue arises at https://github.com/JanusGraph/janusgraph/blob/v0.4/janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java#L145

### PR DESCRIPTION
**Pull request by farodin91**
Fixes #1958

Signed-off-by: Jan Jansen <jan.jansen@gdata.de>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[doc only]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

File: janusgraph-test/src/test/java/org/janusgraph/diskstorage/util/MetricInstrumentedStoreManagerTest.java [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+
+
+@ExtendWith(EasyMockExtension.class)
+public class MetricInstrumentedStoreManagerTest {
+
+    @Mock
+    private KeyColumnValueStoreManager mock;
+
+    @Test
+    public void testGetHadoopManagerReturnsBaseHadoopManager() throws BackendException {
```
Comment (FlorianHockmann) [inline janusgraph-test/src/test/java/org/janusgraph/diskstorage/util/MetricInstrumentedStoreManagerTest.java]: Codacy Issue found: [JUnit tests should include assert() or fail()](https://app.codacy.com/manual/JanusGraph/janusgraph/pullRequest?prid=5019203)

**Comment by FlorianHockmann** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- janusgraph-test/src/test/java/org/janusgraph/diskstorage/util/MetricInstrumentedStoreManagerTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/JanusGraph/janusgraph/pullRequest?prid=5019203&bid=16546448)

File: janusgraph-test/src/test/java/org/janusgraph/diskstorage/util/MetricInstrumentedStoreManagerTest.java [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+
+        MetricInstrumentedStoreManager metricInstrumentedStoreManager = new MetricInstrumentedStoreManager(mock, "", true, "");
+
+        Object hadoopManager = metricInstrumentedStoreManager.getHadoopManager();
```
Comment (FlorianHockmann) [inline janusgraph-test/src/test/java/org/janusgraph/diskstorage/util/MetricInstrumentedStoreManagerTest.java]: Codacy Issue found: [Avoid unused local variables such as 'hadoopManager'.](https://app.codacy.com/manual/JanusGraph/janusgraph/pullRequest?prid=5019203)

**Comment by FlorianHockmann** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- janusgraph-test/src/test/java/org/janusgraph/diskstorage/util/MetricInstrumentedStoreManagerTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/JanusGraph/janusgraph/pullRequest?prid=5019203&bid=16546448)

**Comment by FlorianHockmann** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- janusgraph-test/src/test/java/org/janusgraph/diskstorage/util/MetricInstrumentedStoreManagerTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/JanusGraph/janusgraph/pullRequest?prid=5019203&bid=16546448)
