### PR TITLE
Fix range and ordering for has id query [cql-tests] [tp-tests]

### LINKED ISSUE #3047: Filters on ids prevent sorting and limit
- JanusGraph 0.6.1

When vertex IDs are filtered using `has`, the limit, range and order steps don't work:
```
gremlin> graph = JanusGraphFactory.build().set('storage.backend', 'inmemory').open()
gremlin> GraphOfTheGodsFactory.loadWithoutMixedIndex(graph, true)
gremlin> g = graph.traversal()
gremlin> g.V().has("age").id().fold()
==>[4168,8264,12360,16456,8360,12456]

gremlin> g.V().has(T.id, P.within(4168,8264,12360,16456,8360,12456)).limit(2)
==>v[4168]
==>v[8264]
==>v[12360]
==>v[16456]
==>v[8360]
==>v[12456]

gremlin> g.V().hasId(4168).limit(0)
==>v[4168]

gremlin> g.V().has(T.id, P.within(4168,8264,12360,16456,8360,12456)).order().by("age").values("age")
==>10000
==>4500
==>30
==>4000
==>5000
==>45
```
Explain of the query:
```
g.traversal().V().hasId(4096).limit(0).explain()
==>Traversal Explanation
============================================================================================================================
Original Traversal                                     [GraphStep(vertex,[]), HasStep([~id.eq(4096)]), RangeGlobalStep(0,0)]

ConnectiveStrategy                               [D]   [GraphStep(vertex,[]), HasStep([~id.eq(4096)]), RangeGlobalStep(0,0)]
IdentityRemovalStrategy                          [O]   [GraphStep(vertex,[]), HasStep([~id.eq(4096)]), RangeGlobalStep(0,0)]
EarlyLimitStrategy                               [O]   [GraphStep(vertex,[]), HasStep([~id.eq(4096)]), RangeGlobalStep(0,0)]
MatchPredicateStrategy                           [O]   [GraphStep(vertex,[]), HasStep([~id.eq(4096)]), RangeGlobalStep(0,0)]
FilterRankingStrategy                            [O]   [GraphStep(vertex,[]), HasStep([~id.eq(4096)]), RangeGlobalStep(0,0)]
InlineFilterStrategy                             [O]   [GraphStep(vertex,[]), HasStep([~id.eq(4096)]), RangeGlobalStep(0,0)]
IncidentToAdjacentStrategy                       [O]   [GraphStep(vertex,[]), HasStep([~id.eq(4096)]), RangeGlobalStep(0,0)]
AdjacentToIncidentStrategy                       [O]   [GraphStep(vertex,[]), HasStep([~id.eq(4096)]), RangeGlobalStep(0,0)]
ByModulatorOptimizationStrategy                  [O]   [GraphStep(vertex,[]), HasStep([~id.eq(4096)]), RangeGlobalStep(0,0)]
RepeatUnrollStrategy                             [O]   [GraphStep(vertex,[]), HasStep([~id.eq(4096)]), RangeGlobalStep(0,0)]
CountStrategy                                    [O]   [GraphStep(vertex,[]), HasStep([~id.eq(4096)]), RangeGlobalStep(0,0)]
PathRetractionStrategy                           [O]   [GraphStep(vertex,[]), HasStep([~id.eq(4096)]), RangeGlobalStep(0,0)]
LazyBarrierStrategy                              [O]   [GraphStep(vertex,[]), HasStep([~id.eq(4096)]), RangeGlobalStep(0,0)]
AdjacentVertexFilterOptimizerStrategy            [P]   [GraphStep(vertex,[]), HasStep([~id.eq(4096)]), RangeGlobalStep(0,0)]
AdjacentVertexHasIdOptimizerStrategy             [P]   [GraphStep(vertex,[]), HasStep([~id.eq(4096)]), RangeGlobalStep(0,0)]
AdjacentVertexIsOptimizerStrategy                [P]   [GraphStep(vertex,[]), HasStep([~id.eq(4096)]), RangeGlobalStep(0,0)]
AdjacentVertexHasUniquePropertyOptimizerStrategy [P]   [GraphStep(vertex,[]), HasStep([~id.eq(4096)]), RangeGlobalStep(0,0)]
JanusGraphLocalQueryOptimizerStrategy            [P]   [GraphStep(vertex,[]), HasStep([~id.eq(4096)]), RangeGlobalStep(0,0)]
JanusGraphStepStrategy                           [P]   [JanusGraphStep(vertex,[4096])]
JanusGraphMultiQueryStrategy                     [P]   [JanusGraphStep(vertex,[4096])]
JanusGraphMixedIndexCountStrategy                [P]   [JanusGraphStep(vertex,[4096])]
JanusGraphIoRegistrationStrategy                 [P]   [JanusGraphStep(vertex,[4096])]
ProfileStrategy                                  [F]   [JanusGraphStep(vertex,[4096])]
StandardVerificationStrategy                     [V]   [JanusGraphStep(vertex,[4096])]

Final Traversal                                        [JanusGraphStep(vertex,[4096])]
```
The RangeGlobalStep was removed in the final traversal.

The range and order steps work if IDs are in V(): `g.V(4096,8192,12288,16384,20480).limit(2).count()` returns 2

Moreover, I notice that the index backend is not used when IDs are provided. I think the performance of queries with high number of IDs that have extra filters (using full-text for example) and sorting could be improved if index is used.

### PR DESCRIPTION
**Pull request by li-boxuan**
Fixes #3047

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Comment by li-boxuan** [comment]
This PR targets the 0.6 branch but I didn't include it in the v0.6 milestone so that we don't consider it as a blocker for the 0.6.2 release.

File: janusgraph-test/src/test/java/org/janusgraph/graphdb/query/QueryTest.java [hunk 1]
```diff
@@ -158,6 +160,30 @@ public void testIdLookUpQuery() {
...
+
+        // vertices lookup followed by order step
+        assertEquals(Arrays.asList(20, 30), tx.traversal().V().order().by("age").values("age").toList());
+        assertEquals(Arrays.asList(20, 30), tx.traversal().V().has(T.id, P.within(vId, v2Id)).order().by("age").values("age").toList());
+        assertEquals(Arrays.asList(20, 30), tx.traversal().V().has(T.id, P.within(vId, v2Id)).order().by("age").values("age").toList());
+        assertEquals(Arrays.asList(20, 30), tx.traversal().V().hasId(vId, v2Id).order().by("age").values("age").toList());
+        assertEquals(Arrays.asList(20, 30), tx.traversal().V().hasId(vId, v2Id).order().by("age").values("age").toList());
+
+        // FIXME: vertices lookup in Or query
+        // assertEquals(1, tx.traversal().V().or(__.hasId(vId), __.has("pos", 100)).count().next());
```
Comment (li-boxuan) [inline janusgraph-test/src/test/java/org/janusgraph/graphdb/query/QueryTest.java:180]: This is another bug I found when fixing this issue. I can reproduce the bug on the master branch. Since this is an unrelated bug, I'd like to create a new issue for it.

**Review by porunov — APPROVED** [review]
LGTM. Thank you for fixing this bug @li-boxuan !

**Review by FlorianHockmann — APPROVED** [review]
LGTM and I also suggest that we include this in the 0.6.2 release because it would definitely be good to have this bug fixed soon and I also don't really see a reason to rush the release.
I just merged the PR for the release before seeing this PR, but I guess it shouldn't be a problem to still merge this PR and then proceed with the release process.

**Review by farodin91 — APPROVED** [review]
LGTM! thank you @li-boxuan
