### PR TITLE
[janusgraph-core] fixes properties step in multi-query

### LINKED ISSUE #3081: Similar issue with JanusGraphPropertiesStep related to #2762
This issue seems very similar to #2762 but for the `JanusGraphPropertiesStep`... 

For confirmed bugs, please report:
- Version: 0.6.2
- Storage Backend: cql
- Mixed Index Backend: (es)
- Expected Behavior: _query return_
- Current Behavior: `java.lang.IllegalArgumentException: Need to add at least one vertex to query`
- Steps to Reproduce: Add following test:

```
@Test
public void testPropertiesAfterProjectWithByThenChoose() {
    clopen(option(USE_MULTIQUERY),true,
        option(BATCH_PROPERTY_PREFETCHING),false,
        option(STORAGE_BATCH),false
    );
    long timestamp = System.currentTimeMillis();
    tx.traversal().addV("test").property("a", timestamp).next();
    newTx();
    assertTrue(tx.traversal().V().has("a", timestamp).project("a").by(__.choose(__.has("a"), __.values("a"))).hasNext());
}
```

### Stack Trace (if you have one)

```
java.lang.IllegalArgumentException: Need to add at least one vertex to query
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at org.janusgraph.graphdb.query.vertex.MultiVertexCentricQueryBuilder.execute(MultiVertexCentricQueryBuilder.java:104)
	at org.janusgraph.graphdb.query.vertex.MultiVertexCentricQueryBuilder.properties(MultiVertexCentricQueryBuilder.java:148)
	at org.janusgraph.graphdb.tinkerpop.optimize.step.JanusGraphPropertiesStep.prefetchNextBatch(JanusGraphPropertiesStep.java:120)
	at org.janusgraph.graphdb.tinkerpop.optimize.step.JanusGraphPropertiesStep.flatMap(JanusGraphPropertiesStep.java:132)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.FlatMapStep.processNextStart(FlatMapStep.java:49)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:150)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:226)
	at org.apache.tinkerpop.gremlin.process.traversal.util.TraversalUtil.test(TraversalUtil.java:98)
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.TraversalFilterStep.filter(TraversalFilterStep.java:63)
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.FilterStep.processNextStart(FilterStep.java:38)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:150)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.hasNext(ExpandableStepIterator.java:47)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.HasNextStep.processNextStart(HasNextStep.java:39)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:135)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:40)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.next(DefaultTraversal.java:240)
	at org.apache.tinkerpop.gremlin.process.traversal.util.TraversalUtil.apply(TraversalUtil.java:44)
	at org.apache.tinkerpop.gremlin.process.traversal.step.branch.BranchStep.applyCurrentTraverser(BranchStep.java:145)
	at org.apache.tinkerpop.gremlin.process.traversal.step.branch.BranchStep.standardAlgorithm(BranchStep.java:131)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ComputerAwareStep.processNextStart(ComputerAwareStep.java:46)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:150)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:226)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.CoalesceStep.flatMap(CoalesceStep.java:58)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.FlatMapStep.processNextStart(FlatMapStep.java:49)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:135)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:40)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.next(DefaultTraversal.java:240)
	at org.apache.tinkerpop.gremlin.process.traversal.util.TraversalUtil.apply(TraversalUtil.java:112)
	at org.apache.tinkerpop.gremlin.process.traversal.util.TraversalUtil.applyNullable(TraversalUtil.java:149)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.TreeStep.projectTraverser(TreeStep.java:84)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.TreeStep.projectTraverser(TreeStep.java:45)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ReducingBarrierStep.processAllStarts(ReducingBarrierStep.java:111)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ReducingBarrierStep.processNextStart(ReducingBarrierStep.java:140)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:150)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:226)
	at org.apache.tinkerpop.gremlin.server.util.TraverserIterator.fillBulker(TraverserIterator.java:69)
	at org.apache.tinkerpop.gremlin.server.util.TraverserIterator.hasNext(TraverserIterator.java:56)
	at org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor.handleIterator(TraversalOpProcessor.java:302)
	at org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor.lambda$iterateBytecodeTraversal$0(TraversalOpProcessor.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

### PR DESCRIPTION
**Pull request by lionelfleury**
- add test
- add fix when empty vertices to prefetch

Closes #3081

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you written and/or updated unit tests to verify your changes?

### CODE REVIEW

File: janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java [hunk 1]
```diff
@@ -7409,4 +7409,20 @@ public void testVerticesDropAfterWhereWithBatchQueryEnabled() {
         assertFalse(tx.traversal().V().has("a", timestamp).has("b", true).has("c", true).bothE().hasNext());
     }
 
+    @Test
+    public void testPropertiesAfterProjectWithByThenChoose() {
```
Comment (li-boxuan) [inline janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java:7413]: Nitpick: Can you add `withBatchQueryEnabled` or something similar to the test name, so that people know this test aims to test batch functionality?

**Review by li-boxuan — APPROVED** [review]
LGTM 👍

File: janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java [hunk 2]
```diff
@@ -7409,4 +7409,20 @@ public void testVerticesDropAfterWhereWithBatchQueryEnabled() {
...
+            option(STORAGE_BATCH),false
+        );
+
+        long timestamp = System.currentTimeMillis();
+
+        tx.traversal().addV("test").property("a", timestamp).next();
+
+        newTx();
+
+        assertTrue(tx.traversal().V().has("a", timestamp).project("a").by(__.choose(__.has("a"), __.values("a"))).hasNext());
```
Comment (porunov) [inline janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java:7425]: I guess this check could be without `choose` step but this check with `choose` step looks good as well.
```
tx.traversal().V().has("a", timestamp).project("a").by(__.has("a").values("a")).hasNext()
```

**Review by porunov — APPROVED** [review]
LGTM. Thank you @lionelfleury for this bug fix!
I have checked that the test fails without this fix.

**Comment by lionelfleury** [comment]
fixed comments.
thanks for the feedbacks.
