### PR TITLE
Fix ElasticSearch INDEX_STORE_NAMES_CACHE should not be shared between instances

### LINKED ISSUE #2102: ElasticSearch INDEX_STORE_NAMES_CACHE is shared between instances
`ElasitcSearchIndex` should not share same `INDEX_STORE_NAMES_CACHE`.

For confirmed bugs, please report:
- Version: 0.5.0, 0.5.1
- Mixed Index Backend: ElasticSearch
- Mailing list Thread URL: https://groups.google.com/forum/#!topic/janusgraph-users/YxR1HY6AbS8
- Steps to Reproduce: Create 2 instances of `ElasticSearchIndex`

### PR DESCRIPTION
**Pull request by porunov**
- Move INDEX_STORE_NAMES_CACHE from static to instance specific scope.
- Add possibility to disable INDEX_STORE_NAMES_CACHE cache

Fixes #2102

Signed-off-by: Oleksandr Porunov <alexandr.porunov@gmail.com>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[doc only]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

File: janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java [hunk 1]
```diff
@@ -243,6 +244,12 @@
         new ConfigOption<>(ELASTICSEARCH_NS, "retry_on_conflict",
             "Specify how many times should the operation be retried when a conflict occurs.", ConfigOption.Type.MASKABLE, 0);
 
+    public static final ConfigOption<Boolean> ENABLE_INDEX_STORE_NAMES_CACHE =
```
Comment (mad) [inline janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java:247]: I think we don't need addition option for that

Simply we may use cache with 10k LRU enties

Comment (porunov) [reply janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java:247]: Did you check performance of 10k LRU cache and concurrentHashMap? I checked that it is faster to get a name from map than making contact for 50k and less entities. What if user has more indexes (unlikely but possible)? In such scenario the will be forced to use cache that is slower than string concatenation.

Comment (porunov) [reply janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java:247]: Also, LRU cache may evict some names which we would like to avoid because it is a permanent cache

Comment (mad) [reply janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java:247]: Yes you right concurrenthashmap mush faster than cache. But is so rare case when user would be change this option by memory usages cause, i think

Comment (porunov) [reply janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java:247]: You are right. Most likely nobody will use this option and most likely it will be `true` for all usecases but I think, it would be good to have this option in case the user has very unusual usecase. 

Also, this optimization was introduced here #1695 . This optimization is really tiny, so, regular user won't see any difference but still it speedups index store name retrieval for about 3-4 times faster for regular usages and reduces memory consumptions for unnecessary string concatenations.
