### PR TITLE
fix: handle BerkeleyJE DB interruption [tp-tests]

### LINKED ISSUE #2120: JanusGraph image stop responding after query timeout
I'm using the default docker image janusgraph/janusgraph:latest (Berkeley and Lucene)
and connecting with gremlin console.

When JanusGraph server exceeded his 'evaluationTimeout' the server stop responding

server error:
```
java.util.concurrent.TimeoutException: Evaluation exceeded the configured 'evaluationTimeout' threshold of 30000 ms or evaluation was otherwise cancelled directly for request [g.V()]
        at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$1(GremlinExecutor.java:316)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:748)
1318978 [pool-6-thread-1] WARN  org.janusgraph.diskstorage.log.kcvs.KCVSLog  - Could not read messages for timestamp [2020-05-24T10:12:30.449Z] (this read will be retried)
org.janusgraph.core.JanusGraphException: Could not execute operation due to backend exception
        at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:56)
        at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:158)
        at org.janusgraph.diskstorage.log.kcvs.KCVSLog$MessagePuller.run(KCVSLog.java:725)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.janusgraph.diskstorage.PermanentBackendException: Could not start BerkeleyJE transaction
        at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEStoreManager.beginTransaction(BerkeleyJEStoreManager.java:163)
        at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEStoreManager.beginTransaction(BerkeleyJEStoreManager.java:47)
        at org.janusgraph.diskstorage.keycolumnvalue.keyvalue.OrderedKeyValueStoreManagerAdapter.beginTransaction(OrderedKeyValueStoreManagerAdapter.java:68)
        at org.janusgraph.diskstorage.log.kcvs.KCVSLog.openTx(KCVSLog.java:319)
        at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:145)
        at org.janusgraph.diskstorage.util.BackendOperation$1.call(BackendOperation.java:161)
        at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:68)
        at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:54)
        ... 9 more
Caused by: com.sleepycat.je.ThreadInterruptedException: (JE 18.3.12) Environment must be closed, caused by: com.sleepycat.je.ThreadInterruptedException: Environment invalid because of previous exception: (JE 18.3.12) /var/lib/janusgraph/data java.lang.InterruptedException THREAD_INTERRUPTED: InterruptedException may cause incorrect internal state, unable to continue. Environment is invalid and must be closed.
        at com.sleepycat.je.ThreadInterruptedException.wrapSelf(ThreadInterruptedException.java:105)
        at com.sleepycat.je.dbi.EnvironmentImpl.checkIfInvalid(EnvironmentImpl.java:1835)
        at com.sleepycat.je.dbi.EnvironmentImpl.checkOpen(EnvironmentImpl.java:1844)
        at com.sleepycat.je.Environment.checkOpen(Environment.java:2697)
        at com.sleepycat.je.Environment.beginTransactionInternal(Environment.java:1409)
        at com.sleepycat.je.Environment.beginTransaction(Environment.java:1383)
        at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEStoreManager.beginTransaction(BerkeleyJEStoreManager.java:146)
        ... 16 more
Caused by: com.sleepycat.je.ThreadInterruptedException: Environment invalid because of previous exception: (JE 18.3.12) /var/lib/janusgraph/data java.lang.InterruptedException THREAD_INTERRUPTED: InterruptedException may cause incorrect internal state, unable to continue. Environment is invalid and must be closed.
        at com.sleepycat.je.latch.LatchImpl.acquireExclusive(LatchImpl.java:67)
        at com.sleepycat.je.tree.IN.latch(IN.java:547)
        at com.sleepycat.je.dbi.CursorImpl.latchBIN(CursorImpl.java:402)
        at com.sleepycat.je.dbi.CursorImpl.cloneCursor(CursorImpl.java:230)
        at com.sleepycat.je.Cursor.beginMoveCursor(Cursor.java:5252)
        at com.sleepycat.je.Cursor.beginMoveCursor(Cursor.java:5259)
        at com.sleepycat.je.Cursor.retrieveNextNoDups(Cursor.java:3550)
        at com.sleepycat.je.Cursor.retrieveNext(Cursor.java:3312)
        at com.sleepycat.je.Cursor.getInternal(Cursor.java:1313)
        at com.sleepycat.je.Cursor.get(Cursor.java:1244)
        at com.sleepycat.je.Cursor.getNext(Cursor.java:1512)

```
after the query been sent to server and timeout exceeded other queries which worked before gets same response

`Evaluation exceeded the configured 'evaluationTimeout' threshold of 30000 ms or evaluation was otherwise cancelled directly for request [g.V().limit(4).valueMap()]: null - try increasing the timeout with the :remote command`

### PR DESCRIPTION
**Pull request by tien**
Currently, any interruption to BerkeleyJE DB will cause Janusgraph to stop working entirely & require a complete restart of Janusgraph. This PR will make it so interruption to BerkeleyJE DB will close & reopen the Berkeley's environment instead.

Fixes #2120

### CODE REVIEW

**Comment by tien** [comment]
Update: I was able to write a test to consistently trigger the error n prove that my change should work.

**Comment by tien** [comment]
Have made a change to only re/initialize on interruption.

**Comment by tien** [comment]
Oops, forgot to enable my test since it works now, have done so.

**Comment by tien** [comment]
@li-boxuan @porunov all tests passed, can you guys take a look 👀? Keen to get this merged soon 💪.

**Comment by li-boxuan** [comment]
I am sorry but I seem to have missed some context. Do you know why @mad 's previous PR didn't pass the test, and what did you do differently to solve the problem?

**Comment by tien** [comment]
> I am sorry but I seem to have missed some context. Do you know why @mad 's previous PR didn't pass the test, and what did you do differently to solve the problem?

@li-boxuan I'm not sure why that one didn't pass the test. I'm using a completely different approach in this PR that involves a lot less changes.

File: janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEStoreManager.java [hunk 1]
```diff
@@ -182,15 +195,17 @@ public BerkeleyJETx beginTransaction(final BaseTransactionConfig txCfg) throws B
             }
 
             return btx;
+        } catch (ThreadInterruptedException e) {
+            initialize();
```
Comment (li-boxuan) [inline janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEStoreManager.java:199]: I am a bit confused. Why do we initialize again and then throw exception?

Comment (tien) [reply janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEStoreManager.java:199]: `ThreadInterruptedException` exception means that the BerkeleyJE DB environment is no longer valid, `intialize()` will close and then reopen the `environment` so that subsequent transactions can work.

My reason for throwing here is because I think we should just leave a failed request as failed. And leave any retrying logic to the client.

**Comment by mad** [comment]
Thanks for your contribution!

For proper testing, you need to disable test filtering [here](https://github.com/JanusGraph/janusgraph/pull/3990/files#diff-45fa57a74f390fd8df1d26b15b09bfae64ecae79bce96baf1b74b0304d366af2L25), [here](https://github.com/JanusGraph/janusgraph/pull/3990/files#diff-54e3bb714ade38aba4e19d5db5350902e8b6ddc058e0e1a0361c03fb331144ebL25) and [here](https://github.com/JanusGraph/janusgraph/pull/3990/files#diff-74e5efef2770d32a4554dcea2a6f0644bee1640216b192a8ea7d24756c154a65L25) 

To be completely correct, you still need to disable [this](https://github.com/JanusGraph/janusgraph/pull/3990/files#diff-565bb86939e60f2485aff30c458114482b37ef1d2f50d4ba5b994e22f083205bL114)

**Comment by tien** [comment]
Thank you @mad, I have committed the suggested changes.

**Comment by tien** [comment]
> Thanks for your contribution!
> 
> For proper testing, you need to disable test filtering [here](https://github.com/JanusGraph/janusgraph/pull/3990/files#diff-45fa57a74f390fd8df1d26b15b09bfae64ecae79bce96baf1b74b0304d366af2L25), [here](https://github.com/JanusGraph/janusgraph/pull/3990/files#diff-54e3bb714ade38aba4e19d5db5350902e8b6ddc058e0e1a0361c03fb331144ebL25) and [here](https://github.com/JanusGraph/janusgraph/pull/3990/files#diff-74e5efef2770d32a4554dcea2a6f0644bee1640216b192a8ea7d24756c154a65L25)
> 
> To be completely correct, you still need to enabld [this](https://github.com/JanusGraph/janusgraph/pull/3990/files#diff-565bb86939e60f2485aff30c458114482b37ef1d2f50d4ba5b994e22f083205bL114) (supportsInterruption)

Look like doing this will actually fail the tests. Do you have any idea why?

**Comment by tien** [comment]
@mad @li-boxuan I have implemented the interruption retry logic.

File: janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEStoreManager.java (hunk 1 above)
Comment (tien) [reply janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEStoreManager.java:198]: I have implemented the interruption retry logic. Let me know what you think.

**Comment by tien** [comment]
tp-test are failing, is there anyway I can run n debug these locally?

**Comment by li-boxuan** [comment]
> is there anyway I can run n debug these locally?

I never figured out a great way to debug tp-tests. Others might be able to help. The way I do is to find the corresponding test suite in tinkerpop repository, and run all the tests from there. An adhoc way is to copy that test suite class (.java) file to janusgraph repo on your local machine, and run tests from there. This way, you can remove other unrelated test classes...

**Comment by tien** [comment]
@mad I've checked out the error, in this case it's at initialization:

```
Caused by: org.janusgraph.diskstorage.PermanentBackendException: Error during BerkeleyJE initialization: 
at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEStoreManager.initialize(BerkeleyJEStoreManager.java:151)
at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEStoreManager.<init>(BerkeleyJEStoreManager.java:102)
... 15 more
Caused by: com.sleepycat.je.EnvironmentFailureException: (JE 18.3.12) JAVA_ERROR: Java Error occurred, recovery may not be possible.
```

Unlike the error described in #2120 

```
com.sleepycat.je.ThreadInterruptedException: Environment invalid because of previous exception: (JE 18.3.12) /var/lib/janusgraph/data java.lang.InterruptedException THREAD_INTERRUPTED: InterruptedException may cause incorrect internal state, unable to continue. Environment is invalid and must be closed.
```

I don't think this Berkeley DB can be recovered here by closing and reopening the environment.

So BerkeleyJE DB indeed can't be interrupted in all cases.

Should I undo the all the test filtering changes?

Also cc @li-boxuan

**Comment by tien** [comment]
@mad @li-boxuan

I have patched up the logic some more so that now the only failing error for the `TraversalInterruptionComputerTest` test suite is:

```
java.lang.IllegalStateException: Database was closed.
        at com.sleepycat.je.Database.checkOpen(Database.java:2393)
        at com.sleepycat.je.Database.removeCursor(Database.java:2377)
        at com.sleepycat.je.Cursor.close(Cursor.java:554)
        at org.janusgraph.diskstorage.berkeleyje.BerkeleyJETx.closeCursor(BerkeleyJETx.java:71)
        at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEKeyValueStore.closeCursor(BerkeleyJEKeyValueStore.java:100)
        at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEKeyValueStore$1.close(BerkeleyJEKeyValueStore.java:212)
        at org.janusgraph.diskstorage.keycolumnvalue.keyvalue.OrderedKeyValueStoreAdapter$KeyIteratorImpl.close(OrderedKeyValueStoreAdapter.java:358)
        at org.janusgraph.diskstorage.keycolumnvalue.scan.MultiThreadsRowsCollector$DataPuller.run(MultiThreadsRowsCollector.java:232)
```

Which will invole making BerkeleyJE DB fully interruptible, to which I think is out of the scope for this PR.

**Comment by tien** [comment]
I've integrated some of the other changes from @mad, so the interruption test suite should pass now. cc @mad @li-boxuan

**Comment by tien** [comment]
Hmm, look like there was one last flaky test in the interruption test.

This test parameter in the `TraversalInterruptionTest` & `TraversalInterruptionComputerTest` is failing sometime locally for me, which look like it did fail on the CI:

```java
{"g_E_properties", (Function<GraphTraversalSource, GraphTraversal<?,?>>) g -> g.E(), (UnaryOperator<GraphTraversal<?,?>>) t -> t.properties()}
```

Will investigate, getting close, just 1 case left that need to pass 💪.

**Comment by tien** [comment]
Okay, I've made further changes, after which I haven't been able to reproduce any failure when running the test locally. Hopefully that means the flakiness has gone away 😅.

**Comment by tien** [comment]
Oops, forgot to check other tests beside interruption, made I mistake, have pushed a fix.

**Comment by tien** [comment]
Have made the best effort implementation, so BerkeleyJE DB environment will be reset after interruption & also that race condition around thread are covered so that the interruption test from tp-test will always works.

**Comment by tien** [comment]
@li-boxuan @porunov all tests passed :D

There's the coverage check, but I don't think I can get it any higher though, cuz a lot of the uncovered code are catch clauses. Which are impossible to trigger consistently.

**Comment by li-boxuan** [comment]
Codecov sometimes seems buggy and we don't know why. Don't worry about that. Congrats on passing all tests! @mad would you be able to take another look?

**Review by mad — APPROVED** [review]
Thanks for finishing the job!

**Comment by tien** [comment]
Awesome, thanks for all the helps and supports guys 🙏

**Comment by li-boxuan** [comment]
I am gonna merge this following lazy merge consensus. Thank you @tien for fixing this!

**Comment by janusgraph-automations** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|v1.0|[](https://github.com/JanusGraph/janusgraph/pull/4455)|

Note: Successful backport PRs will be merged automatically after passing CI.

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport) and see the [Github Action logs](https://github.com/JanusGraph/janusgraph/actions/runs/9075171009) for details

**Comment by porunov** [comment]
After merging this PR `tp-tests` are not failing in `master` branch for berkleyje. 

```
Error:  Errors: 
Error:  org.apache.tinkerpop.gremlin.process.traversal.TraversalInterruptionTest.shouldRespectThreadInterruptionInVertexStep[expectInterruption(g_V_outE)]
[INFO]   Run 1: PASS
Error:    Run 2: TraversalInterruptionTest>AbstractGremlinTest.tearDown:155 » LockTimeout (JE 18.3.12) Lock expired. Locker 1229014061 2150_main_Txn: waited for lock on database=_jeNameMap LockAddr:617727493 LSN=0x0/0x1167 type=WRITE grant=WAIT_NEW timeoutMillis=500 startTime=1715693374163 endTime=1715693374663
```

I will try to re-run those tests again. If they don't pass we should revert this commit.

**Comment by tien** [comment]
> After merging this PR `tp-tests` are not failing in `master` branch for berkleyje.
> 
> ```
> Error:  Errors: 
> Error:  org.apache.tinkerpop.gremlin.process.traversal.TraversalInterruptionTest.shouldRespectThreadInterruptionInVertexStep[expectInterruption(g_V_outE)]
> [INFO]   Run 1: PASS
> Error:    Run 2: TraversalInterruptionTest>AbstractGremlinTest.tearDown:155 » LockTimeout (JE 18.3.12) Lock expired. Locker 1229014061 2150_main_Txn: waited for lock on database=_jeNameMap LockAddr:617727493 LSN=0x0/0x1167 type=WRITE grant=WAIT_NEW timeoutMillis=500 startTime=1715693374163 endTime=1715693374663
> ```
> 
> I will try to re-run those tests again. If they don't pass we should revert this commit.

I'm pretty sure this is just a flaky error due to Berkeley DB can't handle many concurrent reads/writes, which now happen cuz we no longer exclude it from some of the tests.

**Comment by porunov** [comment]
> > After merging this PR `tp-tests` are not failing in `master` branch for berkleyje.
> > ```
> > Error:  Errors: 
> > Error:  org.apache.tinkerpop.gremlin.process.traversal.TraversalInterruptionTest.shouldRespectThreadInterruptionInVertexStep[expectInterruption(g_V_outE)]
> > [INFO]   Run 1: PASS
> > Error:    Run 2: TraversalInterruptionTest>AbstractGremlinTest.tearDown:155 » LockTimeout (JE 18.3.12) Lock expired. Locker 1229014061 2150_main_Txn: waited for lock on database=_jeNameMap LockAddr:617727493 LSN=0x0/0x1167 type=WRITE grant=WAIT_NEW timeoutMillis=500 startTime=1715693374163 endTime=1715693374663
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I will try to re-run those tests again. If they don't pass we should revert this commit.
> 
> I'm pretty sure this is just a flaky error due to Berkeley DB can't handle many concurrent reads/writes, which now happen cuz we no longer exclude it from some of the tests.
> 
> Like I can see that this pass https://github.com/JanusGraph/janusgraph/actions/runs/9075171201/job/24965523610 But this run got the time-out error https://github.com/JanusGraph/janusgraph/actions/runs/9075171201/job/24965524860
> 
> Look like a whole other issue: #1623

Yes, tests for berkeleyje with Java 8 passed after restart, but failed again for Java 11. I restarted the job again for Java 11.
We should probably increase those timeouts as I see `timeoutMillis=500` which is probably isn't enough for berkeleyje in GitHub Actions sometimes.

**Comment by tien** [comment]
@porunov I can see that it failed again :(

It's like a flaky race condition where the test try to create an entirely new Berkeley DB graph when the previous one is still invalid/re-intializing. This won't be supported by this PR: this PR simply try to reinitialize the current instance.

This won't happen in production because you'll most likely & should have only one Janusgraph with Berkeley DB instance up and running.

Maybe we should just continue what we did before and disable this particular test for BerkeleyDB?

Or push on with the flaky test, It has always pass for me when I run this locally :p

**Comment by porunov** [comment]
This PR is going to be reverted in #4702 after `tp-tests` I unsure that the revert fixed `tp-tests`. If anyone wish to keep the changes in this PR, feel free to resolve broken `tp-tests` for BerkeleyJE storage backend.
