### PR TITLE
Revert to clearing instead of dropping Solr collection

### LINKED ISSUE #554: JanusGraphFactory:dropStorage deletes Solr cloud core, which cannot recreated by Janus
Introduced under https://github.com/JanusGraph/janusgraph/commit/8522787d6fabd08784105a5937aa83b66d9daa5a#diff-84ae066f641a0f2d5e0e9e726acca7b4

Up to now Solr cloud collection was not completely removed by ``dropStorage`` method. Right now it is. 
The problem is, **Janus can drop the collection, but later it cannot re-create it** while building mixedIndex

properties
````
# storage backend
gremlin.graph=org.janusgraph.core.JanusGraphFactory
storage.backend=cassandrathrift
storage.hostname=192.168.99.100
schema.default=none

# index backend
index.search.backend=solr
index.search.solr.mode=cloud
index.search.solr.zookeeper-url=192.168.99.100:2181
index.search.solr.wait-searcher=true
````

In my case the removed collection is the only one defined on Solr. 
Dropping it means it has to be recreated manually which is not acceptable for Junit testing, where dropStorage method is supposed to be used.

````
JanusGraph graph = JanusGraphFactory.open(config);
JanusGraphFactory.drop(janusGraph);

graph = JanusGraphFactory.open(config);
JanusGraphManagement mgmt = graph.openManagement().
mgmt.buildIndex("collectionName").addKey(....).buildMixedIndex("search");
````

Gives an exception:

````
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://192.168.99.100:8983/solr: Can not find the specified config set: collectionName
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:610) ~[solr-solrj-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:32:54]
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:279) ~[solr-solrj-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:32:54]
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:268) ~[solr-solrj-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:32:54]
	at org.apache.solr.client.solrj.impl.LBHttpSolrClient.doRequest(LBHttpSolrClient.java:447) ~[solr-solrj-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:32:54]
	at org.apache.solr.client.solrj.impl.LBHttpSolrClient.request(LBHttpSolrClient.java:388) ~[solr-solrj-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:32:54]
	at org.apache.solr.client.solrj.impl.CloudSolrClient.sendRequest(CloudSolrClient.java:1383) ~[solr-solrj-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:32:54]
	at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:1134) ~[solr-solrj-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:32:54]
	at org.apache.solr.client.solrj.impl.CloudSolrClient.request(CloudSolrClient.java:1073) ~[solr-solrj-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:32:54]
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:160) ~[solr-solrj-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:32:54]
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:177) ~[solr-solrj-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:32:54]
	at org.janusgraph.diskstorage.solr.SolrIndex.createCollectionIfNotExists(SolrIndex.java:1039) ~[janusgraph-solr-0.2.0-SNAPSHOT.jar:?]
	at org.janusgraph.diskstorage.solr.SolrIndex.register(SolrIndex.java:301) ~[janusgraph-solr-0.2.0-SNAPSHOT.jar:?]
	at org.janusgraph.diskstorage.indexing.IndexTransaction.register(IndexTransaction.java:101) ~[janusgraph-core-0.2.0-SNAPSHOT.jar:?]
	at org.janusgraph.graphdb.database.IndexSerializer.register(IndexSerializer.java:107) ~[janusgraph-core-0.2.0-SNAPSHOT.jar:?]
	at org.janusgraph.graphdb.database.management.ManagementSystem.addIndexKey(ManagementSystem.java:547) ~[janusgraph-core-0.2.0-SNAPSHOT.jar:?]
	at org.janusgraph.graphdb.database.management.ManagementSystem$IndexBuilder.buildMixedIndex(ManagementSystem.java:660) ~[janusgraph-core-0.2.0-SNAPSHOT.jar:?]
...
````

Possible solutions:
- clear all items in collection without dropping collection definition
- least give an option to drop only Janus storage backend only (restore previous behavior possibly under a different method)

### PR DESCRIPTION
**Pull request by sjudeng**
Fixes #554

### CODE REVIEW

File: janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java [hunk 1]
```diff
@@ -870,8 +870,10 @@ public void clearStorage() throws BackendException {
             final ClusterState clusterState = zkStateReader.getClusterState();
             for (final String collection : clusterState.getCollectionsMap().keySet()) {
                 logger.debug("Clearing collection [{}] in Solr",collection);
-                final CollectionAdminRequest.Delete request = CollectionAdminRequest.deleteCollection(collection);
-                solrClient.request(request, collection);
+                // Collection is not dropped because it may have been created externally
+                final UpdateRequest deleteAll = newUpdateRequest();
+                deleteAll.deleteByQuery("*:*");
```
Comment (davidclement90) [inline janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java]: I'm not a great user of Solr, but I think is not a good idea to use delete by query.
I think it's the same as Elasticsearch, on large index delete by query will take days to be perform (https://www.elastic.co/guide/en/elasticsearch/reference/current/_deleting_documents.html).

I think the problem is not when JanusGraph drop the collection, but when it can not re-create it.

For me this code will have big performance issue and it's a good practice when for example you reindexing to drop the collection.

Comment (sjudeng) [reply janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java]: @davidclement90 I'm not a Solr user myself either. But the [docs](https://wiki.apache.org/solr/FAQ#How_can_I_delete_all_documents_from_my_index.3F) indicate this as the method to delete all documents so I wonder if the implementation is more efficient than Elasticsearch delete by query. The update here restores the original implementation removed in https://github.com/JanusGraph/janusgraph/pull/499/commits/8522787d6fabd08784105a5937aa83b66d9daa5a.

JanusGraph is able to create the collection but it assumes the same name for the Solr config set parameter (or uses a global config set). It doesn't support a per-collection config set parameter. Perhaps we can create another issue to add support for this? The other thing on this is that this only applies to Solr Cloud. With Solr HTTP, which might be the more common access mode, JanusGraph does not support clearing at all (deleting documents or dropping collection).

Comment (pluradj) [reply janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java]: Right, the original implementation is restored, so it's the same as the previous behavior.

**Comment by sjudeng** [comment]
@davidclement90 I created #570 to track work on adding support for specifying the configset as an index creation parameter, which I think would enable us to rely on JanusGraph for Solr collection creation (and therefore dropping) more exclusively.
