### PR TITLE
Fix StaticArrayEntryTest.testToStringWithNoValue hex long leading zero flaky test

### LINKED ISSUE #2248: Flaky test StaticArrayEntryTest.testToStringWithNoValue
## Flaky Test

* **Test Name:** `StaticArrayEntryTest.testToStringWithNoValue`
* **Link:** https://github.com/JanusGraph/janusgraph/blob/a852ca89b7a23ccbe95c59800c5c3e8b088afeb9/janusgraph-test/src/test/java/org/janusgraph/diskstorage/util/StaticArrayEntryTest.java#L49
* **Branch:** `master`

### Stack Trace

```
[ERROR] Failures: 

[ERROR]   StaticArrayEntryTest.testToStringWithNoValue:49 expected: <0x35D200728821E4E> but was: <0x035D200728821E4E>

[INFO] 

[ERROR] Tests run: 416, Failures: 1, Errors: 0, Skipped: 2
```

### PR DESCRIPTION
**Pull request by porunov**
Fixes #2248

Signed-off-by: Oleksandr Porunov <alexandr.porunov@gmail.com>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[doc only]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

File: janusgraph-test/src/test/java/org/janusgraph/diskstorage/util/StaticArrayEntryTest.java [hunk 1]
```diff
@@ -39,14 +39,22 @@ public void testToString() {
...
     @Test
-    public void testToStringWithNoValue() {
-        long l = random.nextLong();
+    public void testRandomLongToStringWithNoValue() {
+        testToStringWithNoValue(random.nextLong());
+    }
+
+    @Test
+    public void testHexLongWithLeadingZeroToStringWithNoValue() {
+        testToStringWithNoValue(242385170064350798L);
```
Comment (li-boxuan) [inline janusgraph-test/src/test/java/org/janusgraph/diskstorage/util/StaticArrayEntryTest.java:48]: Shall we use a less "magical" number here, e.g. `Long.MAX_VALUE >> 3` (which has 15 "F"s in hex format)?

**Review by li-boxuan — APPROVED** [review]
LGTM 👍  Just left a small comment

File: janusgraph-test/src/test/java/org/janusgraph/diskstorage/util/StaticArrayEntryTest.java (hunk 1 above)
Comment (porunov) [reply janusgraph-test/src/test/java/org/janusgraph/diskstorage/util/StaticArrayEntryTest.java]: I got this value from one of the failing tests but you are right, `Long.MAX_VALUE >> 3` is less confusing. Changed that to `Long.MAX_VALUE >> 3`
