### PR TITLE
Issue 862 Fix preferred default timestamp provider logic in janusgraph configuration 

### LINKED ISSUE #862: Fix 'preferred default' timestamp provider logic in janusgraph configuration
As commented in #663, the 'preferred default' timestamp provider logic does not work.
We need to fix it.

```
public static final ConfigOption<TimestampProviders> TIMESTAMP_PROVIDER = new ConfigOption<>(GRAPH_NS, "timestamps",
      "The timestamp resolution to use when writing to storage and indices. Sets the time granularity for the " +
      "entire graph cluster. To avoid potential inaccuracies, the configured time resolution should match " +
      "those of the backend systems. Some JanusGraph storage backends declare a preferred timestamp resolution that " +
      "reflects design constraints in the underlying service. When the backend provides " +
      "a preferred default, and when this setting is not explicitly declared in the config file, the backend " +
      "default is used and the general default associated with this setting is ignored.  An explicit " +
      "declaration of this setting overrides both the general and backend-specific defaults.",
      ConfigOption.Type.FIXED, TimestampProviders.class, TimestampProviders.MICRO);
```
Particularly:
When the backend provides a preferred default, and when this setting is not explicitly declared in the config file, the backend default is used and the general default associated with this setting is ignored.

### PR DESCRIPTION
**Pull request by jerryjch**
Fix #862

Signed-off-by: Jerry He <jinghe@us.ibm.com>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by jerryjch** [comment]
@sjudeng Could I please get some review?

File: janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/graphdb/hbase/HBaseGraphTest.java [hunk 1]
```diff
@@ -41,4 +46,17 @@ public void testVertexTTLImplicitKey() { }
     @Override @Test @Ignore("HBase does not support retrieving cell TTL by client")
     public void testEdgeTTLImplicitKey() { }
 
+    @Test
+    public void testHBaseTimestampProvider() {
```
Comment (sjudeng) [inline janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/graphdb/hbase/HBaseGraphTest.java]: This test passes even without the updates to GraphDatabaseConfiguration. It looks like it hits the `else` condition (see [Codecov](https://codecov.io/gh/JanusGraph/janusgraph/src/timestamp-provider/janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java#L1405)) instead of the `if` condition that I think needs to be checked to test the issue/fix.

**Comment by jerryjch** [comment]
@sjudeng thanks for the review.  I will take a look as soon as I have a  chance.

**Comment by pluradj** [comment]
any updates on this @jerryjch?

**Comment by jerryjch** [comment]
@pluradj Do you mean to add something to the http://docs.janusgraph.org/latest/upgrade.html
Or somewhere in the HBase section?

File: docs/upgrade.adoc [hunk 2]
```diff
@@ -103,3 +103,14 @@ configuration properties.
...
 no longer supported in JanusGraph 0.2.0. Users should refer to the previous
 sections and migrate to the `REST_CLIENT`.
+
+=== Upgrading from JanusGraph 0.2.0
+
+==== HBase TTL
+
+In JanusGraph 0.2.0, time-to-live (TTL) support was added for HBase storage backend.
+In order to utilize the TTL capability on HBase, the graph timestamps need to be
+MILLI. If the graph.timestamps property is not explicitly set to MILLI, the default
```
Comment (pluradj) [inline docs/upgrade.adoc]: backticks around `graph.timestamps`

**Comment by jerryjch** [comment]
@pluradj Fixed the nit in the new commit.  Will commit after the check is finished.
Thanks for all the reviews!
