### PR TITLE
Make DateSerializer thread-safe

### LINKED ISSUE #2429: DateSerializer is not thread-safe
Setup
- Version: 0.5.3
- Storage Backend: cql
- Mixed Index Backend: elasticsearch

Under production load, our JanusGraph cluster failed to process from 1 to 30 requests / hour due to ElasticSearch receiving invalid dates (`+0000-01-31T08:49:54.000+0000`):
```
org.janusgraph.core.JanusGraphException: Could not process individual retrieval call
[...]
    Caused by: org.janusgraph.diskstorage.PermanentBackendException: Permanent failure in storage backend
    at org.janusgraph.diskstorage.es.ElasticSearchIndex.query(ElasticSearchIndex.java:1117)
    at org.janusgraph.diskstorage.indexing.IndexTransaction.queryStream(IndexTransaction.java:108)
    at org.janusgraph.diskstorage.BackendTransaction$6.call(BackendTransaction.java:416)
    at org.janusgraph.diskstorage.BackendTransaction$6.call(BackendTransaction.java:413)
    at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:68)
    at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:54)
    ... 49 common frames omitted
    Caused by: org.elasticsearch.client.ResponseException: method [POST], host [...], URI [/.../_search?scroll=60s], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"parse_exception","reason":"failed to parse date field [+0000-01-31T08:49:54.000+0000] with format [strict_date_optional_time||epoch_millis]: [failed to parse date field [+0000-01-31T08:49:54.000+0000] with format [strict_date_optional_time||epoch_millis]]"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"...","node":"...","reason":{"type":"parse_exception","reason":"failed to parse date field [+0000-01-31T08:49:54.000+0000] with format [strict_date_optional_time||epoch_millis]: [failed to parse date field [+0000-01-31T08:49:54.000+0000] with format [strict_date_optional_time||epoch_millis]]","caused_by":{"type":"illegal_argument_exception","reason":"failed to parse date field [+0000-01-31T08:49:54.000+0000] with format [strict_date_optional_time||epoch_millis]","caused_by":{"type":"date_time_parse_exception","reason":"date_time_parse_exception: Failed to parse with all enclosed parsers"}}}}]},"status":400}
    at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:283)
    at org.elasticsearch.client.RestClient.performRequest(RestClient.java:261)
    at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235)
    at org.janusgraph.diskstorage.es.rest.RestElasticSearchClient.performRequest(RestElasticSearchClient.java:483)
    at org.janusgraph.diskstorage.es.rest.RestElasticSearchClient.search(RestElasticSearchClient.java:467)
    at org.janusgraph.diskstorage.es.rest.RestElasticSearchClient.search(RestElasticSearchClient.java:437)
    at org.janusgraph.diskstorage.es.rest.RestElasticSearchClient.search(RestElasticSearchClient.java:60)
    at org.janusgraph.diskstorage.es.ElasticSearchIndex.query(ElasticSearchIndex.java:1108)
    ... 54 common frames omitted
```

I tracked down the issue and was able to reproduce it with the following unit test:
```
public class DateSerializerTest {
    private final StandardSerializer serializer = new StandardSerializer();

    @Test
    public void dateSerializerConvertStringThreadSafe() throws Exception {
        ExecutorService pool = Executors.newFixedThreadPool(64);
        String input = "2021-01-30T17:30:31.000";
        Date reference = StdDateFormat.instance.parse(input);

        List<Future<Date>> futures = new ArrayList<>();
        try {
            // Have serializer parse the same date 100x in parallel
            for (int i = 0; i < 100; ++i) {
                futures.add(pool.submit(() -> serializer.convert(Date.class, input)));
            }
            for (Future<Date> future : futures) {
                assertEquals(reference, future.get());
            }
        } finally {
            pool.shutdown();
        }
    }
}
```

The unit test fails due to partial date matches such as:
```
org.opentest4j.AssertionFailedError: 
Expected :Sat Jan 30 18:30:31 CET 2021
Actual   :Fri Jan 01 18:30:31 CET 2021
```
```
org.opentest4j.AssertionFailedError: 
Expected :Sat Jan 30 18:30:31 CET 2021
Actual   :Thu Jan 01 01:00:00 CET 1970
```

I think `DateSerializer` is not thread-safe because [`StdDateFormat.instance#parse`](https://github.com/JanusGraph/janusgraph/blob/3223efd9b717f4aa9415e82628aca5e906999134/janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/attribute/DateSerializer.java#L59) [reuses a Calendar instance](https://github.com/FasterXML/jackson-databind/pull/1759) that is not thread-safe.

There are multiple ways to solve this (confirmed by the above unit test passing):
- Wrap `dateFormat.parse` in a synchronized block/method
- Store StdDateFormat in a ThreadLocal or create new local instances
- Use Java 8+ DateTimeFormatter (if so, do we want to remain compatible with the RFC-1123 format that StdDateFormat handled?)

### PR DESCRIPTION
**Pull request by cdegroc**
Fixes #2429

Signed-off-by: Clement de Groc <clement.degroc@datadoghq.com>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there an issue associated with this PR? Is it referenced in the commit message?
- [X] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [X] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Comment by li-boxuan** [comment]
@farodin91 Seems multiple PRs are failing due to 

>  Error:    JanusGraphScriptIT.testGraphOfTheGodsGraphSONFull:26->JanusGraphAssemblyBaseIT.unzipAndRunExpect:102->JanusGraphAssemblyBaseIT.unzipAndRunExpect:73->JanusGraphAssemblyBaseIT.parseTemplateAndRunExpect:95->JanusGraphAssemblyBaseIT.expect:113->JanusGraphAssemblyBaseIT.command:152 expected: <0> but was: <1>

Would you be able to take a look at it?

**Comment by farodin91** [comment]
> @farodin91 Seems multiple PRs are failing due to 
> 
> 
> 
> >  Error:    JanusGraphScriptIT.testGraphOfTheGodsGraphSONFull:26->JanusGraphAssemblyBaseIT.unzipAndRunExpect:102->JanusGraphAssemblyBaseIT.unzipAndRunExpect:73->JanusGraphAssemblyBaseIT.parseTemplateAndRunExpect:95->JanusGraphAssemblyBaseIT.expect:113->JanusGraphAssemblyBaseIT.command:152 expected: <0> but was: <1>
> 
> 
> 
> Would you be able to take a look at it?

I will provide an pull request. If you want to fix it quick check for the newest Cassandra version and replace the version in janusgraph dist.

**Comment by cdegroc** [comment]
Rebased on master to have the new Cassandra version.

**Review by li-boxuan — APPROVED** [review]
LGTM 👍 
From [this discussion](https://www.mail-archive.com/jackson-dev@googlegroups.com/msg00320.html) it seems we shouldn't have used this StdDateFormat in the first place, but this fix/workaround looks good to me.

**Comment by cdegroc** [comment]
> LGTM 👍
> From [this discussion](https://www.mail-archive.com/jackson-dev@googlegroups.com/msg00320.html) it seems we shouldn't have used this StdDateFormat in the first place, but this fix/workaround looks good to me.

Agree. It would be cleaner to switch to Java 8+ DateTimeFormatter but, to remain backward compatible, we'd have to try both ISO-8601 and RFC-1123 date/time patterns. Or just discard the RFC-1123 pattern.

**Comment by li-boxuan** [comment]
Merged by following lazy consensus.

File: janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/attribute/DateSerializer.java [hunk 1]
```diff
@@ -26,7 +26,8 @@
 public class DateSerializer implements OrderPreservingSerializer<Date> {
 
     private final LongSerializer ls = LongSerializer.INSTANCE;
-    private final StdDateFormat dateFormat = StdDateFormat.instance;
+    // StdDateFormat is not thread-safe
+    private static final ThreadLocal<StdDateFormat> dateFormat = ThreadLocal.withInitial(StdDateFormat::new);
```
Comment (porunov) [inline janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/attribute/DateSerializer.java:30]: Didn't check the logic but wanted to say that ThreadLocal data is not released if the thread is killed / stopped.
Which means that we can see data leak here if we don't properly remove threadlocal data

Comment (cdegroc) [reply janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/attribute/DateSerializer.java:30]: Hey @porunov. Good point. Glad you mentioned it. I'll open another PR to fix this.

Comment (li-boxuan) [reply janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/attribute/DateSerializer.java:30]: Hi is there any resource that explains how/why ThreadLocal data is not garbage collected for a dead thread?

Comment (porunov) [reply janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/attribute/DateSerializer.java:30]: Quickly reading javadoc I'm now in doubt about my words. Will need to check more info later. Maybe I'm just wrong. I do remember memory leaks with ThreadLocal  but maybe it's only reproducible with cached thread pool. I will check that later

Comment (cdegroc) [reply janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/attribute/DateSerializer.java:30]: Here is a reference (from Sonar) to leaks happening when re-using threads: https://rules.sonarsource.com/java/RSPEC-5164
If you believe there is a leak, and as already mentioned on this PR/issue, we can always switch to using the thread-safe Java 8+ DateTimeFormatter.

I've created a branch with a candidate change set: https://github.com/JanusGraph/janusgraph/compare/master...cdegroc:java-date-time-formatterhttps://github.com/JanusGraph/janusgraph/compare/master...cdegroc:java-date-time-formatter

Comment (li-boxuan) [reply janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/attribute/DateSerializer.java:30]: > I do remember memory leaks with ThreadLocal 

I think you are referring to the case where the transaction (or even janusgraph) is closed but the thread (likely part of an externally managed thread pool) is reused for other affairs. E.g. https://github.com/JanusGraph/janusgraph/issues/1341

Given this StdDateFormat shouldn't be used in the first place since it is intended for internal use only, I agree we should switch to alternative solutions. That being said, I haven't reviewed @cdegroc 's thread-safe solution yet.
