### PR TITLE
Replace Spark KryoRegistrator with TP KryoShimService

### LINKED ISSUE #373: Geoshape properties can't be deserialized in OLAP mode
A KryoException is thrown when attempting to deserialize any Geoshape properties in OLAP mode because Geoshape is missing a no-arg constructor.

```
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Exception while getting task result: java.io.IOException: org.apache.tinkerpop.shaded.kryo.KryoException: Class cannot be created (missing no-arg constructor): org.janusgraph.core.attribute.Geos
hape
Serialization trace:
value (org.apache.tinkerpop.gremlin.structure.util.detached.DetachedVertexProperty)
properties (org.apache.tinkerpop.gremlin.structure.util.detached.DetachedVertex)
t (org.apache.tinkerpop.gremlin.process.traversal.traverser.B_O_Traverser)
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1431)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1419)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1418)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1418)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
        at scala.Option.foreach(Option.scala:236)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:799)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1640)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1599)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1588)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:620)
```

### PR DESCRIPTION
**Pull request by sjudeng**
Fixes #373

### CODE REVIEW

**Comment by sjudeng** [comment]
@twilmes It looks like serialization of Geoshape predicates in OLAP traversals has never been supported? I checked JanusGraph 0.1 and Titan 1.0 and both failed with the same error. I think the underlying issue is that when the traversal has a Geoshape predicate it forces the Geoshape into the task's closure, and Spark does not support Kryo for closure serialization.

https://issues.apache.org/jira/browse/SPARK-12414
https://stackoverflow.com/a/40261550

Can we create a separate issue for adding support for Geoshape predicates in OLAP traversals? The current updates here fix #373 (e.g. OLAP traversals with Geoshape properties), which I view as a bug fix since this worked in 0.1

File: janusgraph-dist/src/assembly/static/bin/gremlin.sh [hunk 1]
```diff
@@ -98,7 +98,7 @@ if [ -z "${HADOOP_GREMLIN_LIBS:-}" ]; then
 fi
 
 if [ -z "${JAVA_OPTIONS:-}" ]; then
-    JAVA_OPTIONS="-Dtinkerpop.ext=$EXT -Dlog4j.configuration=conf/log4j-console.properties -Dgremlin.log4j.level=$GREMLIN_LOG_LEVEL -javaagent:$LIB/jamm-0.3.0.jar"
+    JAVA_OPTIONS="-Dtinkerpop.ext=$EXT -Dlog4j.configuration=conf/log4j-console.properties -Dgremlin.log4j.level=$GREMLIN_LOG_LEVEL -javaagent:$LIB/jamm-0.3.0.jar -Dgremlin.io.kryoShimService=org.janusgraph.hadoop.serialize.JanusGraphKryoShimService"
```
Comment (sjudeng) [inline janusgraph-dist/src/assembly/static/bin/gremlin.sh]: @twilmes Yep, done. Thanks!

**Comment by twilmes** [comment]
Yeah, that sounds good to me, I created #390 to cover this.
