### PR TITLE
Use JanusGraphManager by default

### LINKED ISSUE #2822: storage.hostname and index.[x].hostname don't work with multiple hostnames
It seems to be no longer possible to configure multiple hostnames for the storage or index backend in version 0.6.0.

For confirmed bugs, please report:
- Version: 0.6.0
- Storage Backend: CQL
- Mixed Index Backend: elasticsearch
- Link to discussed bug: -
- Expected Behavior: Add all hostnames as individual contact points
- Current Behavior: The hostnames are treated as a single hostname which results in this WARN log:
```
 WARN  com.datastax.oss.driver.internal.core.ContactPoints  - Ignoring invalid contact point testhost1,testhost2:9042 (unknown host testhost1,testhost2)
```
The same happens for index.[x].hostname with elasticsearch.
- Steps to Reproduce: Start JanusGraph Server with a config `.properties` file that contains a list of hostnames for `storage.cql.hostname` or `index.[x].hostname`.

`storage-cql-es.properties`:

```
storage.hostname=testhost1,testhost2
index.search.hostname=testhost1,testhost2
```

This bug must have been introduced in 0.6.0 as it used to work in version 0.5.3.

### PR DESCRIPTION
**Pull request by FlorianHockmann**
This makes it possible to use comma-separated config values again, e.g., for `storage.hostname`.
The `DefaultGraphManager` from TinkerPop used until now uses the TinkerPop `GraphFactory` which uses `DisabledListDelimiterHandler`. So, comma separated config values are not supported with that `GraphManager`. `JanusGraphFactory` however uses comma-delimited `DefaultListDelimiterHandler`.
So, switching from TinkerPop's `DefaultGraphManager` to `JanusGraphManager` which uses the `JanusGraphFactory` allows to use comma-separated config values again.

Fixes #2822

The tests in `JanusGraphServerTest` all initialize a graph manager instance which is why they cannot be moved to `JanusGraphManager` as that is a singleton implementation which throws when a second instance is requested and the instance is not returned at any point. So, I didn't change those tests to also use the `JanusGraphManager`.

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Comment by FlorianHockmann** [comment]
If we merge this, then we should also change the YAML for janusgraph-docker here: https://github.com/JanusGraph/janusgraph-docker/blob/master/build/conf/janusgraph-server.yaml

File: janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/AbstractGremlinServerIntegrationTest.java [hunk 1]
```diff
@@ -48,7 +48,7 @@
     private static final Logger logger = LoggerFactory.getLogger(AbstractGremlinServerIntegrationTest.class);
 
     public String getSettingsPath() {
-        return "src/test/resources/gremlin-server-integration.yaml";
+        return "src/test/resources/janusgraph-server-integration.yaml";
```
Comment (rngcntr) [inline janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/AbstractGremlinServerIntegrationTest.java:51]: The naming is a little bit unconvenient here: In the integration tests, `gremlin-server-[...].yaml` was renamed to `janusgraph-server-[...].yaml`, while in `janusgraph-dist/`, all config files are still named `gremlin-server-[...].yaml`.

**Review by rngcntr — COMMENTED** [review]
Looks good, just one little remark

File: janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/AbstractGremlinServerIntegrationTest.java (hunk 1 above)
Comment (FlorianHockmann) [reply janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/AbstractGremlinServerIntegrationTest.java:51]: Oh right, I thought that they were named `janusgraph-server-[...].yaml` already in the distribution, but then I'll also change the name back here.

**Review by farodin91 — APPROVED** [review]

**Review by rngcntr — APPROVED** [review]

**Review by porunov — APPROVED** [review]

File: docs/changelog.md [hunk 2]
```diff
@@ -41,6 +41,71 @@ The versions of JanusGraph listed below are outdated and will no longer receive
...
+* [JanusGraph zip with embedded Cassandra and ElasticSearch](https://github.com/JanusGraph/janusgraph/releases/download/v0.6.1/janusgraph-full-0.6.1.zip)
+
+#### Upgrade Instructions
+
+##### GraphManager changed to JanusGraphManager
+
+A `GraphManager` is used to instantiate graph instances. JanusGraph Server has used the
+`DefaultGraphManager` from TinkerPop for this by default if no other `GraphManager` was specified
+in the JanusGraph Server YAML config file.
+A recent change in how this `DefaultGraphManager` parses config values made it impossible to
```
Comment (li-boxuan) [inline docs/changelog.md:90]: Shall we be more specific here to avoid confusion, for example, mention that this change is introduced by JanusGraph 0.6.0/TinkerPop 3.5.0?

Comment (FlorianHockmann) [reply docs/changelog.md]: Good idea! I added these two releases explicitly.
