### PR TITLE
Fix neq and null condition query behavior

### LINKED ISSUE #2205: neq behaviour differs from TinkerGraph
TinkerPop added a test which now fails with JanusGraph. 
In our case we assume that if there is no property with the specified name in `has` step with `neq` predicate than the result is `true` but TinkerGraph assumes that if there is no such property the result should always be `false`.

The related discussion with @spmallette: https://github.com/apache/tinkerpop/commit/76fc5c23e72b7ad9faafb1faab836ce1ac1259d2#r42228711

As we need to alight with TinkerPop, I believe we need to change the behaviour on neq step to preserve compatibility.

For confirmed bugs, please report:
- Version: 0.5.2, 0.6.0-SNAPSHOT
- Storage Backend: All
- Mixed Index Backend: N/A
- Mailing list Thread URL: https://groups.google.com/g/gremlin-users/c/DbuJ0Drt0Ec/m/fg6WJ_SwAwAJ
- Steps to Reproduce: 

```
gremlin> graph=JanusGraphFactory.open("inmemory")
==>standardjanusgraph[inmemory:[127.0.0.1]]
gremlin> graph.addVertex()
==>v[4344]
gremlin> graph.traversal().V().has("p", neq("v"))
18:51:57 WARN  org.janusgraph.graphdb.transaction.StandardJanusGraphTx  - Query requires iterating over all vertices [()]. For better performance, use indexes
==>v[4344]
gremlin>
gremlin> graph=TinkerGraph.open()
==>tinkergraph[vertices:0 edges:0]
gremlin> graph.addVertex()
==>v[0]
gremlin> graph.traversal().V().has("p", neq("v"))
gremlin> 
```

### PR DESCRIPTION
**Pull request by li-boxuan**
Fixes #2205

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[doc only]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

File: janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java [hunk 1]
```diff
@@ -5792,18 +5792,6 @@ private static void assertElementOrderForWithoutIndex(StandardJanusGraph graph)
...
-    @Test
-    public void testHasNot() {
-        JanusGraphVertex v1, v2;
-        v1 = graph.addVertex();
-
-        v2 = graph.query().hasNot("abcd").vertices().iterator().next();
-        assertEquals(v1, v2);
-        v2 = graph.query().hasNot("abcd", true).vertices().iterator().next();
-        assertEquals(v1, v2);
-    }
```
Comment (porunov) [inline janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java:5805]: Why this test was removed from `JanusGraphTest.java`? Tests in `JanusGraphTest.java` are executed against different storages backends. I guess, it would be better to just fix this test instead of removing it

File: janusgraph-driver/src/main/java/org/janusgraph/core/attribute/Cmp.java [hunk 2]
```diff
@@ -73,10 +73,13 @@ public boolean isValidCondition(Object condition) {
...
+            if (value == null) {
+                // To align with TinkerPop behaviour, if an element does not have property p, then has(p, neq(anything))
+                // should always evaluate to false. Note that JanusGraph does not support null value, so the "value == null"
+                // here implies the element does not have such property.
+                return false;
             } else {
-                return !condition.equals(value);
+                return !value.equals(condition);
             }
         }
```
Comment (porunov) [inline janusgraph-driver/src/main/java/org/janusgraph/core/attribute/Cmp.java:84]: I guess, slightly simplified version would be:
```
@Override
public boolean test(Object value, Object condition) {
    // To align with TinkerPop behaviour, if an element does not have property p, then has(p, neq(anything))
    // should always evaluate to false. Note that JanusGraph does not support null value, so the "value == null"
    // here implies the element does not have such property.
    return value != null && !value.equals(condition);
}
```

**Comment by porunov** [comment]
Other than above two comments the code LGTM. Checked that added tests fail without changes with some index backends (as expected).

File: janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java (hunk 1 above)
Comment (li-boxuan) [reply janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java:5805]: It is moved to `JanusGraphIndexTest` because I want to enforce the existence of indexes does not alter the behavior. Example: https://github.com/JanusGraph/janusgraph/issues/1868#issuecomment-694933702

Comment (porunov) [reply janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java:5805]: What about behaviour without any index? As I understand, this logic was tested with use cases when there is no necessary indices

Comment (li-boxuan) [reply janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java:5805]: That is also tested. See [testHasNot](https://github.com/JanusGraph/janusgraph/pull/2265/files#diff-e22cf3f57c2f67c294951e7c0318ad14f06ae190ec0237e8076784198ddb8685R251) in JanusGraphIndexTest.

**Comment by li-boxuan** [comment]
After this PR, tinkerpop version can be upgraded to 3.4.8 without test failure.  https://travis-ci.org/github/li-boxuan/janusgraph/builds/747943340 (ignore first failure which always happens on my Travis)

File: janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java (hunk 1 above)
Comment (porunov) [reply janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java:5805]: I don't have strong opinion here. `testHasNot` which you removed was tested against different storage backends (CQL, BerkleyDB, HBase, InMemory). In the new `testHasNot` method we test it with several combinations CQL or BerkleyDB as a storage backend and Lucene / Solr / ElasticSearch as index backend. Thus, now the test is executed with less storage backends. 
As I said, I don't have strong opinion here. If you think it's better to keep all that test logic in one place (`JanusGraphIndexTest`) and don't test against InMemory and HBase I'm fine with it. I thought, maybe it's better to split that test logic between `JanusGraphTest` and `JanusGraphIndexTest`. For example, test cases `property not registered in schema`, `property registered in schema` and `property registered in schema and has composite index` can easily be moved to `JanusGraphTest` where they will be executed against a bigger number of Storage backends whereas `property registered in schema and has mixed index` can be in `JanusGraphIndexTest` where it will be executed against different mixed index backends.

Comment (li-boxuan) [reply janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java:5805]: That's fair. The initial thought was to avoid having similar tests in both classes, but you made a valid point. I'll move some back to JanusGraphTest.

File: janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java [hunk 3]
```diff
@@ -5792,16 +5792,100 @@ private static void assertElementOrderForWithoutIndex(StandardJanusGraph graph)
...
+        assertTrue(tx.traversal().V().has("p2", (Object) null).hasNext());
+        // property registered in schema and has composite index
+        assertTrue(tx.traversal().V().has("p3", (Object) null).hasNext());
+    }
 
+    /**
+     * The behaviour of hasNot(p) is straight-forward: hasNot(p) means it does not have such property p.
+     * Note that hasNot(p, value) (which is a JanusGraph API rather than gremlin API) is a bit tricky and it is equivalent
+     * to has(p, neq(value)). Therefore, hasNot(p, null) means has(p, neq(null)) which is equivalent to has(p).
+     */
```
Comment (porunov) [inline janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java:5844]: Doesn't `hasNot` is Gremlin API?
https://tinkerpop.apache.org/javadocs/3.4.8/core/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.html#hasNot-java.lang.String-

Comment (porunov) [reply janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java:5844]: Ah sorry, missed second parameter

**Review by porunov — APPROVED** [review]
LGTM. Thank you @li-boxuan !
