### PR TITLE
Bug fixes: relations cannot be removed after update

### LINKED ISSUE #1981: Modified vertex property is not removed after remove operation
If the property is modified and then removed in the same transaction, it won't be removed in the storage backend.

For confirmed bugs, please report:
- Version: 0.5.0-SNAPSHOT
- Storage Backend: ScyllaDB 3.2.1 (not important)
- Mixed Index Backend: ElasticSearch 6.8.6 (not important)
- Mailing list Thread URL: https://groups.google.com/forum/#!topic/janusgraph-users/c4AAydzlEV4
- Steps to Reproduce: 

```
@Test
public void testRemoveVertexPropertyAfterModification() {

    Vertex v = graph.addVertex();
    v.property("name", "name1");
    graph.tx().commit();

    v = graph.traversal().V(v.id()).next();
    v.property("name", "name2");
    v.property("name").remove();
    graph.tx().commit();

    assertFalse(graph.traversal().V(v.id()).values("name").hasNext());
}
```

As seen from the example above, the `name` property isn't removed even so we called `remove` before the commit.

### PR DESCRIPTION
**Pull request by li-boxuan**
This commit includes fixes for three bugs:

1) Caused by the optimization in StandardJanusGraphTx::addProperty, which saves a database
read (and delete) operation for vertex property upsert. If a vertex property (or the vertex
as a whole) is removed after the property is modified in the same transaction, then the old
value in database will not be deleted after the transaction commits. Reported by #1981.

2) Caused by CacheVertexProperty::remove method which does nothing if it finds the given
vertex property is already in the deletedRelations map. If the user deletes a vertex property
after they update a nested property of that vertex property in the same transaction, then
the old value will be removed from database but the new value will be saved into database
after the transaction commits.

3) Caused by CacheEdge::remove method which does nothing if it finds the given edge is
already in the deletedRelations map. If the user deletes an edge after they update a property
of that edge in the same transaction, then the old value will be removed from database but the
new value will be saved into database after the transaction commits.
-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[doc only]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Review by li-boxuan — COMMENTED** [review]
Added some comments to explain the changes:

File: janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphVertexProperty.java [hunk 1]
```diff
@@ -45,4 +47,16 @@ default PropertyKey propertyKey() {
         return (PropertyKey)getType();
     }
 
+    static Consumer<JanusGraphVertexProperty> getRemover(VertexProperty.Cardinality cardinality, Object value) {
+        if (cardinality == VertexProperty.Cardinality.single) {
+            return JanusGraphElement::remove;
```
Comment (porunov) [inline janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphVertexProperty.java:52]: I don't know much about how lambda are compiled but if it is changed to `new Consumer<JanusGraphVertexProperty> {....}` shouldn't this consumer be static? I don't think we need to create a new instance of this consumer because it doesn't reuse any other parameters.
I.e., I think it would be better to create a static consumer like:
```
private static Consumer<JanusGraphVertexProperty> SINGLE_PROPERTY_REMOVER_CONSUMER = JanusGraphElement::remove; 
```
and reuse `SINGLE_PROPERTY_REMOVER_CONSUMER` here. That said, if you know that `JanusGraphElement::remove` will be compiled to static consumer, I'm totally good with it.

**Review by porunov — COMMENTED** [review]
Great work @li-boxuan ! Thank you!
I made a very quick pass and I have a small question below

File: janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphVertexProperty.java (hunk 1 above)
Comment (li-boxuan) [reply janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphVertexProperty.java:52]: Looks like it is compiled to static consumer:

```java
boolean sameObject = false;
Consumer<JanusGraphVertexProperty> c1 = null;
for (int i = 0; i < 2; i++) {
    Consumer<JanusGraphVertexProperty> c2 = new Consumer<JanusGraphVertexProperty>() {
        @Override
        public void accept(JanusGraphVertexProperty p) {
            p.remove();
        }
    };
    if (c1 == null) c1 = c2;
    else sameObject = c1 == c2; // false
}
```

when using method reference or lambda function, result is different:

```java
boolean sameObject = false;
Consumer<JanusGraphVertexProperty> c1 = null;
for (int i = 0; i < 2; i++) {
    Consumer<JanusGraphVertexProperty> c2 = JanusGraphElement::remove;
    if (c1 == null) c1 = c2;
    else sameObject = c1 == c2; // true
}
```

Example modified from https://stackoverflow.com/questions/23983832/is-method-reference-caching-a-good-idea-in-java-8/23991339#23991339

Comment (porunov) [reply janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphVertexProperty.java:52]: Thank you for checking that!

File: janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java [hunk 2]
```diff
@@ -798,14 +798,13 @@ public JanusGraphVertexProperty addProperty(VertexProperty.Cardinality cardinali
 //                }
 //            }
 
+            long propId = id == null ? IDManager.getTemporaryRelationID(temporaryIds.nextID()) : id;
+            StandardVertexProperty prop = new StandardVertexProperty(propId, key, (InternalVertex) vertex, normalizedValue, ElementLifeCycle.New);
+            if (config.hasAssignIDsImmediately() && id == null) graph.assignID(prop);
+
```
Comment (porunov) [inline janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java:804]: Why did you move this logic from bottom to up?

File: janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/StandardVertexProperty.java [hunk 3]
```diff
@@ -101,6 +114,11 @@ public synchronized void remove() {
         if (!ElementLifeCycle.isRemoved(lifecycle)) {
             tx().removeRelation(this);
             lifecycle = ElementLifeCycle.update(lifecycle, ElementLifeCycle.Event.REMOVED);
+            if (isUpsert) {
+                VertexProperty.Cardinality cardinality = ((PropertyKey) type).cardinality().convert();
+                Consumer<JanusGraphVertexProperty> propertyRemover = JanusGraphVertexProperty.getRemover(cardinality, value());
+                getVertex(0).query().types(type.name()).properties().forEach(propertyRemover);
```
Comment (porunov) [inline janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/StandardVertexProperty.java:120]: I'm good with `getVertex(0)` but maybe it's better to use `element()`?

**Review by porunov — COMMENTED** [review]
Just a couple more questions

File: janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java [hunk 4]
```diff
@@ -816,7 +815,10 @@ public JanusGraphVertexProperty addProperty(VertexProperty.Cardinality cardinali
                 if ( (!config.hasVerifyUniqueness() || ((InternalRelationType)key).getConsistencyModifier()!=ConsistencyModifier.LOCK) &&
                         !TypeUtil.hasAnyIndex(key) && cardinality==keyCardinality.convert()) {
                     //Only delete in-memory so as to not trigger a read from the database which isn't necessary because we will overwrite blindly
-                    ((InternalVertex) vertex).getAddedRelations(p -> p.getType().equals(key)).forEach(propertyRemover);
+                    //We need to label the new property as "upsert", so that in case property deletion happens, we not only delete this new
+                    //in-memory property, but also read from database to delete the old value (if exists)
+                    ((InternalVertex) vertex).getAddedRelations(p -> p.getType().equals(key)).forEach(p -> propertyRemover.accept((JanusGraphVertexProperty) p));
+                    prop.setUpsert(true);
```
[the remark this answers is not in the document]
Comment (li-boxuan) [reply janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java:821]: A property is always "new" when you update its value. You cannot directly set a value to a property object; instead, you can only attach a key-value pair to a vertex object, i.e. `v.property("key", "value")`. 

Thus, the `prop` here is defined by:
`StandardVertexProperty prop = new StandardVertexProperty(propId, key, (InternalVertex) vertex, normalizedValue, ElementLifeCycle.New);` which is always "new".

I believe the scenario you mentioned is already handled as part of this PR, but I am adding a test case to be sure.

File: janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java (hunk 2 above)
Comment (li-boxuan) [reply janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java:804]: because we need to set `prop.setUpsert(true);` later

**Review by porunov — APPROVED** [review]
Great work @li-boxuan ! LGTM.
Just need to wait for TravisCI build to pass

**Comment by porunov** [comment]
@li-boxuan Don't forget to merge this fix to `master` branch as well
