### PR TITLE
Use available page size for CQL result set instead of forced page size [full build]

### LINKED ISSUE #2254: Potential CQL iteration page fetch bug
As described in the DataStax driver docs: https://docs.datastax.com/en/developer/java-driver/3.9/manual/paging/

> Note that setting a fetch size doesn’t mean that Cassandra will always return the exact number of rows, it is possible that it returns slightly more or less results.

Our current implementation assumes that we always return `paginatedResultSize` for all pages except the last one. For the last page it assumes `<=paginatedResultSize`.
Any time we fetched `paginatedResultSize` (which is equal to `storage.page-size`) we are forcing to fetch the next page, as seen here:
https://github.com/JanusGraph/janusgraph/blob/f5001e6210baa15bc136f3224ba1e83521782cba/janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java#L458-L461

It **may** potentially lead to unprocessed rows in case Cassandra returned more elements on the fetched page then set in `paginatedResultSize`. It may also potentially lead to skipping some of the elements on the next page in case the current page contains less elements then `paginatedResultSize` (because the internal driver will prefetch the next page before we actually trigger `getResultSet` and thus we will trigger `getResultSet` while we are processing a second page, which will lead to going straight to the 3rd page without processing the rest of the elements on the second page).

That said, I don't confirm this bug yet but label it as **possible** bug because I didn't confirm that in our case DSE driver returns any other amount of elements on intermediate pages than `paginatedResultSize` amount of elements.
I.e. in case DSE driver returns always `paginatedResultSize` for intermediate pages then I don't see any bug. Otherwise, there is a potential bug.

`CQLPagingIterator` was introduced here https://github.com/JanusGraph/janusgraph/pull/1814
So, this potential bug may affect branches `0.3`, `0.4`, `0.5` and `master`.

Also, notice, this bug will be resolved in `master` branch in this PR https://github.com/JanusGraph/janusgraph/pull/2169 because we change `CQLPagingIterator` in that PR to not relay on `storage.page-size` directly and thus we eliminate that potential bug for `master` branch.
We still may want to fix this **potential** bug in `0.5` branch because we still support it.

For confirmed bugs, please report:
- Version: 0.5
- Storage Backend: CQL
- Mixed Index Backend: -
- Mailing list Thread URL: -
- Steps to Reproduce: -

### PR DESCRIPTION
**Pull request by porunov**
Changes in this PR will be ignored in `master` branch because this *potential* bug is fixed in `master` branch.
In the issue I described why it is hard to confirm and test this bug. This PR either fixes a *potential* bug or does nothing (lets say just refactors the code).

Fixes #2254

Signed-off-by: Oleksandr Porunov <alexandr.porunov@gmail.com>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[doc only]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Review by li-boxuan — APPROVED** [review]
LGTM 👍

**Comment by porunov** [comment]
Looks like it messed some tests. If anyone wants to check that, feel free to do that, otherwise I will check that later

**Comment by li-boxuan** [comment]
I am just thinking: can we just use the same fix you have in https://github.com/JanusGraph/janusgraph/pull/2169 ? getAllExecutionInfo method seems available in Datastax Driver 3.x as well.

**Comment by porunov** [comment]
> I am just thinking: can we just use the same fix you have in #2169 ? getAllExecutionInfo method seems available in Datastax Driver 3.x as well.

Unfortunately no. In Datastax Driver 3.x it returns a new ArrayList instead of returning current ArrayList

File: janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java [hunk 1]
```diff
@@ -441,43 +439,43 @@ public KeyIterator getKeys(final SliceQuery query, final StoreTransaction txh) t
...
         }
 
         @Override
         public boolean hasNext() {
-            return !currentResultSet.isExhausted();
+            if(availableWithoutFetching<=0){
+                if(currentResultSet.isFullyFetched()){
+                    return false;
+                }
+                fetchResultSet();
```
Comment (li-boxuan) [inline janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java:456]: LGTM 👍  I tested locally using the following code which creates and reads 100 thousand vertices. The test passed. I could also see fetchResultSet() is called in hasNext() method.
```java
   @Test
    public void testHugeGraph() {
        int maxK = 100, maxI = 1000;
        for (int k = 0; k < maxK; k++) {
            for (int i = 0; i < maxI; i++) {
                tx.addVertex("prop", k * maxI + i);
                newTx();
            }
        }

        List<Object> props = graph.traversal().V().values("prop").toList();
        assertEquals(maxK * maxI, new HashSet<>(props).size());
    }
```

That being said, I also observed something weird: when I ran this locally, I put a debug point (in Intellij) on this line (line 456) to check if this line is reachable. Once I saw the debug point reached, I immediately removed the debug point and resumed the application. Then the test case failed because `graph.traversal().V().values("prop").toList()` returned fewer results than expected. I could always reproduce it; even when I set `maxI = 10` (that is, one thousand vertices in total). However, the same test case always passes as long as I don't set a debug point. I tried letting the thread sleep for 1 or more seconds here, but the test case still passes. Do you have any thoughts?

Comment (porunov) [reply janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java:456]: It's a default behaviour in Intellij debugger to execute the debugged line to print `toString()` result to convince (most likely you hovered your mouth over this line and thus it executed the line).
In you example, you set a debug point on line 456, then you reach that line and when you hover your mouth it will execute `fetchResultSet()` to check if it can print anything meaningful. After that your resume your debug and go fetching a new page (without actually processing any elements on this page). Basically, calling `fetchResultSet()` 2 times instead of 1 time.
That is why it contains fewer elements (i.e. 1 page fewer elements). Moreover, it's actually can produce more elements (in case you are debugging the last page in multi-page traversal).
That said, it's just some debugging problems and not related to the code directly. Also it's just my assumption, in theory it could be something else

Comment (li-boxuan) [reply janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java:456]: Got it thanks, that makes sense!

**Review by li-boxuan — APPROVED** [review]
